### PR TITLE
Support ruby2.5 runtime

### LINKED ISSUE #1057: Feature request: Support ruby runtime.
Recently AWS announced the support for ruby (2.5) runtime for Lambda. 
Please check https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### PR DESCRIPTION
**Pull request by mhmoudgmal**
On dockerhub (https://hub.docker.com/r/lambci/lambda/tags/) there is already an image for ruby runtime.

Also I've tested these changes using a simple code you can find here [index.zip](https://github.com/localstack/localstack/files/2677574/index.zip)

Closes #1057

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR, thanks @mhmoudgmal ! Any chance we can create a very simple integration test to ensure the Ruby Lambda execution actually works? `test_lambda.py` would be a good starting point - similar to the tests for the Node.JS Lambda runtime: https://github.com/localstack/localstack/blob/master/tests/integration/test_lambda.py#L205 . Thanks

**Comment by mhmoudgmal** [comment]
@whummer Oh yeah absolutely! just haven't paid enough attention that we have tests for lambda runtimes 😂 OK.. how about refactoring the tests to use `unittest` as well?

**Comment by whummer** [comment]
> how about refactoring the tests to use unittest as well?

That would be awesome @mhmoudgmal ! Many thanks

**Comment by mhmoudgmal** [comment]
@whummer Finished refactoring the test file and ended up splitting the tests to multiple classes each contains all related tests, also I though it might be better to have smaller test functions when possible instead of one big monolith test like the one in `TestPythonRuntimes`

Also there was a weird behaviour in this test https://github.com/localstack/localstack/pull/1058/files#diff-3b979538481fa94fbe2a996f76f9e831R195 which was extracted from here https://github.com/localstack/localstack/blob/26f44a79e9bf47c1a24053a32a83480e7eeb9480/tests/integration/test_lambda.py#L145 where I had to change the lambda name of the *test_lambda_py3*  https://github.com/localstack/localstack/pull/1058/files#diff-3b979538481fa94fbe2a996f76f9e831R29.. this what was happening https://travis-ci.org/localstack/localstack/builds/473836138#L2217 couldn't figure out the issue!

--- In order to reproduce this behaviour:
you can change back the name here https://github.com/localstack/localstack/pull/1058/files#diff-3b979538481fa94fbe2a996f76f9e831L23 and run the tests `kk; DEBUG=1 LAMBDA_EXECUTOR=docker-reuse USE_SSL=1 .venv/bin/nosetests tests/integration/test_lambda.py`

and *watch* the containers 
`watch -n 2 "docker ps --format \"table {{.Image}}\t {{.Status}}\t {{.Names}}\""`

it might not be so important as long as it works now, but I will try to spend some time digging deep to understand what is happening.

Also I would suggest not squash these two commits.

**Comment by whummer** [comment]
Thanks for the detailed report @mhmoudgmal . I took a closer look and created follow-up PR #1074 which should fix the issue you described. We'll close this PR and merge the other one (preserving the commits in this PR, though). Thanks again for this feature!

**Comment by mhmoudgmal** [comment]
Awesome! Thanks for applying the features @whummer and tacking care of that issue!  👍 🎉

**Pull request closed without merging**
