### PR TITLE
Fix broken links in CONTRIBUTING.md and README.md

### PR DESCRIPTION
**Pull request by l-melon**
## Motivation
PR for #11101 

## Changes
Fix broken link in CONTRIBUTING.md
- [x] integration testing
- [x] parity testing
- [x] Development Environment Setup
- [x] Contributor License Agreement

## Testing
Open [CONTRIBUTING.md](https://github.com/localstack/localstack/blob/master/docs/CONTRIBUTING.md) and click these link.

### CODE REVIEW

**Comment by l-melon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by l-melon** [comment]
Hi, I'm new here. How do I add a label to a PR?

**Comment by Badg** [comment]
I noticed this the other day and was just about to do this but you beat me to it, nice!

**Review by HarshCasper — APPROVED** [review]

**Comment by thrau** [comment]
thank you for your contribution @l-melon ! :100:

**Comment by l-melon** [comment]
Happy to contribute!

**Pull request merged**
