### PR TITLE
Suppress permission errors for non-root Docker

### PR DESCRIPTION
**Pull request by snmishra**
Potential fix for #5396.

### CODE REVIEW

**Comment by snmishra** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by whummer — COMMENTED** [review]
Nice approach, thanks for tacking this @snmishra ! 👍 

While it makes sense to make the code more resilient against `PermissionError`, I think it would be better to fix the root cause of the issue, namely that the `localstack/infra/...` folders within the Docker container are owned by root and not writable by other users.

Running under a non-root user currently breaks the startup/install routine, as you pointed out:
```
$ DOCKER_FLAGS='--user localstack' DEBUG=1 localstack start
...
File "/opt/code/localstack/localstack/services/install.py", line 525, in install_dynamodb_local
save_file(log4j2_file, log4j2_config)
File "/opt/code/localstack/localstack/utils/files.py", line 64, in save_file
with open(file, mode, opener=_opener if permissions else None) as f:
PermissionError: [Errno 13] Permission denied: '/opt/code/localstack/localstack/infra/dynamodb/log4j2.xml'
```

If we add the following line to our `Dockerfile`:
```
RUN chmod -R 777 localstack/infra/dynamodb
```
... then the startup works fine:
```
$ DOCKER_FLAGS='--user localstack' DEBUG=1 localstack start
...
Ready.
```

(We could apply the same chmod to the entire infra folder, not just `infra/dynamodb`)

/cc @dfangl @alexrashed  @thrau

**Comment by snmishra** [comment]
Thanks for taking a look. I don’t understand how localstack build/install works completely, so I’m probably incorrect in the following assessment.

I assumed that the build (which runs as root) already created all the files necessary. But there are some attempts to write to files at runtime, which fail for non-root. In my limited testing, just suppressing the error lets me run without errors.

**Comment by alexrashed** [comment]
Hi @snmishra!
As @whummer stated above, we should tackle the root cause of the issue by setting the correct permissions in the first place.
Actually, there's already another community contribution addressing the same problem (https://github.com/localstack/localstack/pull/6271) by adjusting the permissions in the Dockerfile. Once our new file system structure is live, we'll try to get this over the line. This is why I'm closing this PR in favor of #6271. Thanks!

**Pull request closed without merging**
