### PR TITLE
Resolve issues with building in Java 9 (and above) environments #1028

### PR DESCRIPTION
**Pull request by AndyMacDroo**
Fix test failures while running in JDK 9 and above due to failure to destroy process from removal of UNIXProcess class in java 9.

### CODE REVIEW

**Comment by AndyMacDroo** [comment]
To prove this branch is actually passing in later java versions, it's probably worth updating the .travis.yml to use openjdk-9. But I thought this was a pretty involved change and warranted some discussion first.

**Comment by AndyMacDroo** [comment]
Thanks to @efenderbosch for the start he made on this here: https://github.com/localstack/localstack/issues/1028

**Comment by AndyMacDroo** [comment]
Helloo @whummer - could this get reviewed?

**Comment by whummer** [comment]
This is great - thanks for this PR @AndyMacDroo ! In a future iteration I guess we could maybe use a more polymorphic approach to reduce the number of if/else checks (one subclass each for pre- and post Java 8). But definitely great to see that this works across Java versions now! We'll release a new version of the Java libs shortly.

**Pull request merged**
