### PR TITLE
Set INITIALIZE_STREAMS for Kinesis Mock

### PR DESCRIPTION
**Pull request by etspaceman**
## Motivation

Fix for #8895 

## Changes

Sets INITIALIZE_STREAMS for the kinesis-mock

<!-- The following sections are optional, but can be useful! 

## Testing

Description of how to test the changes

### CODE REVIEW

**Comment by etspaceman** [comment]
Looks like I can't set labels so many of these checks are failing due to that.

**Review by viren-nadkarni — CHANGES_REQUESTED** [review]
@etspaceman Could you fix the linting with `make format`?

**Comment by viren-nadkarni** [comment]
Not sure why the secrets are not being passed to the jobs.

`docker-test-amd64` and `docker-test-arm64` pass, merging PR.

**Review by viren-nadkarni — APPROVED** [review]

**Comment by alexrashed** [comment]
I'm sorry for the late answer, but just to answer your questions: Secrets are never able to be used by fork builds, because they could quite easily extract the secrets. We should modify our pipelines such that the use of secrets is optional (which they are currently not). Sorry for the inconvenience, and thanks for the contribution! 🚀

**Pull request merged**
