### PR TITLE
fix: remove AWSPREVIOUS only when duplicated

### LINKED ISSUE #10082: bug: SecretsManager removes the AWSPREVIOUS stage label and its version when removing a different stage label
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Given** two versions A and B, and version B has an `AWSPREVIOUS` stage label, **when** a stage label is removed from version A with the `update-secret-version-stage` command, **then** the stage label is removed from version A (as expected) AND version B is removed (unexpectedly). 

### Expected Behavior

The `update-secret-version-stage` command should only affect stage labels specified by the input parameters, and other stage labels, including `AWSPREVIOUS`, should not be affected. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

```
version: '3.4'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - 5670:4566
    environment:
      - DEBUG=1
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint-url=http://127.0.0.1:5670 secretsmanager create-secret \
--name=test \
--secret-string=test \
--region=ap-northeast-1
```

```
aws --endpoint-url=http://127.0.0.1:5670 secretsmanager put-secret-value \
--secret-id=test \
--secret-string=test2 \
--region=ap-northeast-1 \
--version-stages=PENDING
```

```
aws --endpoint-url=http://127.0.0.1:5670 secretsmanager list-secret-version-ids \
--secret-id=test \
--region=ap-northeast-1
```

```
{
    "Versions": [
        {
            "VersionId": "cc279696-7f93-4dc4-99dd-8f8e7112fb37",
            "VersionStages": [
                "PENDING"
            ],
            "CreatedDate": "2024-01-17T17:33:33.601708+09:00"
        },
        {
            "VersionId": "d9b7e6e4-5512-43f8-907f-6ba6623d1094",
            "VersionStages": [
                "AWSCURRENT"
            ],
            "CreatedDate": "2024-01-17T17:33:06.863652+09:00"
        }
    ],
    "ARN": "arn:aws:secretsmanager:ap-northeast-1:000000000000:secret:test-soExxm",
    "Name": "test"
}
```

```
aws --endpoint-url=http://127.0.0.1:5670 secretsmanager update-secret-version-stage \
--secret-id=test \
--region=ap-northeast-1 \
--version-stage=AWSCURRENT \
--remove-from-version-id=d9b7e6e4-5512-43f8-907f-6ba6623d1094 \
--move-to-version-id=cc279696-7f93-4dc4-99dd-8f8e7112fb37
```

```
{
    "Versions": [
        {
            "VersionId": "cc279696-7f93-4dc4-99dd-8f8e7112fb37",
            "VersionStages": [
                "PENDING",
                "AWSCURRENT"
            ],
            "CreatedDate": "2024-01-17T17:33:33.601708+09:00"
        },
        {
            "VersionId": "d9b7e6e4-5512-43f8-907f-6ba6623d1094",
            "VersionStages": [
                "AWSPREVIOUS"
            ],
            "CreatedDate": "2024-01-17T17:33:06.863652+09:00"
        }
    ],
    "ARN": "arn:aws:secretsmanager:ap-northeast-1:000000000000:secret:test-soExxm",
    "Name": "test"
}
```

```
aws --endpoint-url=http://127.0.0.1:5670 secretsmanager update-secret-version-stage \
--secret-id=test \
--region=ap-northeast-1 \
--version-stage=PENDING \
--remove-from-version-id=cc279696-7f93-4dc4-99dd-8f8e7112fb37
```

```
aws --endpoint-url=http://127.0.0.1:5670 secretsmanager list-secret-version-ids \
--secret-id=test \
--region=ap-northeast-1
```

```
{
    "Versions": [
        {
            "VersionId": "cc279696-7f93-4dc4-99dd-8f8e7112fb37",
            "VersionStages": [
                "AWSCURRENT"
            ],
            "CreatedDate": "2024-01-17T17:33:33.601708+09:00"
        }
    ],
    "ARN": "arn:aws:secretsmanager:ap-northeast-1:000000000000:secret:test-soExxm",
    "Name": "test"
}
```

### Environment

```markdown
- OS: MacOS Sonoma 14.2.1
- LocalStack: latest
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vimiomori**
## Motivation
fixes #10082

Localstack currently assumes that any `AWSPREVIOUS` label that wasn't moved by an `UpdateSecretVersionStage` call is a duplicate. However, a new `AWSPREVIOUS` label is added only when the `AWSCURRENT` label is moved. This PR ensures that when a custom stage label is moved, the existing `AWSPREVIOUS` label is not assumed to be a duplicate.

## Changes
1. This PR adds a check to only remove an older `AWSPREVIOUS` label if the updated stage label is `AWSCURRENT`
2. It no longer checks if a version that has the `AWSPREVIOUS` is the version `AWSCURRENT` was moved to because [moto already handles that](https://github.com/localstack/moto/blob/b6bda0a623d28d3b2b454dfbf6664075eb07bc91/moto/secretsmanager/models.py#L899).
3. It no longer assumes that there are only deprecated versions when there is an `AWSPREVIOUS` to remove. It removes all versions without stage labels. 

> [!NOTE]  
> Removing versions without staging labels deviates from AWS's [documented behavior](https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#term_version), but this behavior is preserved in this PR to keep the PR atomic. 
> > Secrets Manager never removes labeled versions, but unlabeled versions are considered deprecated. Secrets Manager removes deprecated versions when there are more than 100. Secrets Manager doesn't remove versions created less than 24 hours ago.
>
> I've raised an issue for this at: https://github.com/localstack/localstack/issues/10086

### CODE REVIEW

**Comment by vimiomori** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vimiomori** [comment]
@dominikschubert @MEPalma 
Hi 👋 May I ask you to review this PR? And if someone may add a `semver:patch` label for me, that would be appreciated. 🙏

Thank you!

**Comment by dominikschubert** [comment]
Hi @vimiomori, I've checked and validated the test you added. During this I've kinda jumped into a bit of a rabbit hole and validated a lot of the other secretsmanager tests. Hope it's fine for you that we included this work in the scope of the PR

**Review by dominikschubert — APPROVED** [review]
LGTM, thanks for your contribution! :partying_face:

**Pull request merged**
