### PR TITLE
limit botocore to < 1.31.81

### PR DESCRIPTION
**Pull request by alexrashed**
## Motivation
With https://github.com/boto/botocore/commit/84c784761d4cde0c0ce3b2b32382f970d23b3cc8#diff-3c03aa9063b20ce7452434106e383aedb840b8b183833425614ca5d3884cc5d0, [botocore](https://github.com/boto/botocore) switched to the JSON protocol for SQS again.
This was already tried with version `1.27.127`: https://github.com/boto/botocore/commit/2395012bd369f89b0bcfbbf830718866fc6ae166
The last time the changes was reverted.
This PR is just a quick workaround to get the pipeline green before https://github.com/localstack/localstack/pull/8268 is over the line.

## Changes
- Limit `botocore < 1.31.81`

### CODE REVIEW

**Review by dominikschubert — APPROVED** [review]
Thanks for unblocking the pipeline :pray: 

Do we want to get https://github.com/localstack/localstack/pull/8268 over the line before the 3.0 release? :thinking:

**Comment by alexrashed** [comment]
Yes, definitely. I am currently looking at it, it should definitely be done before the release. Maybe we can fix it during the day.

**Comment by Jecoms** [comment]
Will this fix be included in a patch release (that could then make its way into the circle orb)?

**Comment by alexrashed** [comment]
If you are using the boto client from _within_ the localstack docker container, then this is already contained in the latest community image (and will shortly land in the latest pro image). We are about to release a major version next week, there is no patch release planned until then.

However, this does not fix any issues to talk to localstack if your client (outside of localstack) is using the new botocore version.
We are currently working on a fix.
Please take a look at https://github.com/localstack/localstack/issues/8267 (which is the issue report for this issue).
You can also follow this PR to get updates on the fix: https://github.com/localstack/localstack/pull/8268

**Pull request merged**
