### PR TITLE
Fix: Alias name validator

### PR DESCRIPTION
**Pull request by deepak2431**
This PR is for the fix of issue #7494 
Initially, there was no validation on alias names done to create an alias. I have added the Alias name validation which would raise a ValidationException if the given alias name doesn't start with "alias/"

@bentsku You can review this.

### CODE REVIEW

**Review by bentsku — CHANGES_REQUESTED** [review]
Hi @deepak2431 and thanks a lot for your contribution!

Would it be possible to add an integration test in `tests/integration/test_kms.py`?

Here's our documentation about contributing: https://docs.localstack.cloud/contributing/contributing/ and writing integration tests: https://docs.localstack.cloud/contributing/integration-tests/

Thank you!

**Comment by deepak2431** [comment]
> Hi @deepak2431 and thanks a lot for your contribution!
> 
> Would it be possible to add an integration test in `tests/integration/test_kms.py`?
> 
> Here's our documentation about contributing: https://docs.localstack.cloud/contributing/contributing/ and writing integration tests: https://docs.localstack.cloud/contributing/integration-tests/
> 
> Thank you!

I have checked it to add integration tests but didn't see any scope. Though, I will check again and see if there's any scope to add it. As the alias name is defined in the fixture only.

**Comment by deepak2431** [comment]
@bentsku I have added the integration test.

**Review by bentsku — APPROVED** [review]
> @bentsku I have added the integration test.

Awesome, this is exactly what we needed, thanks a lot for taking the time to write this test! 
 It's all good to go for me, I'll merge. 👍 congratulations for your first contribution!

**Pull request merged**
