### PR TITLE
Asf sns migration

### PR DESCRIPTION
**Pull request by baermat**
Migrating sns to ASF

### CODE REVIEW

**Comment by baermat** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by baermat** [comment]
Trying to iron out the last hiccups in the pipeline, the failing pro cases work locally for me, and I wanted to get this finally ready for review

**Review by thrau — APPROVED** [review]
well done @baermat! a pretty big migration! i was going to suggest to use `MotoFallbackDispatcher` and remove the methods that only call moto and do nothing else, but in the case of SNS it seems almost better to have it explicitly since it seems the storage is completely fragmented between moto and localstack. definitely something we should clean up moving forward.

**Comment by baermat** [comment]
Ready for tandel release

**Pull request merged**
