### PR TITLE
fix APIGW CFN UsagePlan update operation with Tags

### PR DESCRIPTION
**Pull request by artaban**
Fix for the issue #11510 

## Changes
- Fixed Tags update in **ApiGatewayV1 UsagePlan**

## Testing
- **UsagePlan** tags are updated correctly

## TODO
- not sure if the test is working / testing the change. Has not been able to perform cross-check on my environment.

### CODE REVIEW

**Comment by artaban** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by bentsku — COMMENTED** [review]
Hi @artaban and thanks a lot for the fix and contribution!

The fix looks good, but the test will fail as you would need to regenerate the snapshots taken against AWS. Also, I don't think that is where we need to test this, as the issue is related to CloudFormation, and the test case added is testing directly the operation `UpdateUsagePlan`. 

There is however a specific test for that in `tests.aws.services.cloudformation.resources.test_apigateway.test_update_usage_plan` that fits your need.

You can modify the CloudFormation template to add tags, and validate the fix there. The template lives in `tests/aws/templates/apigateway_usage_plan.yml`. 

If regenerating the snapshots against AWS is an issue, I'll update them once you update the test. Thank you again!

**Comment by bentsku** [comment]
Hey @artaban, thanks a lot for adding it to the template! I've pushed some changes to validate the test against AWS and came across an issue in our implementation where we actually did not call `tag_resource` to update the tags. I've fixed it as our current implementation was not doing what it was supposed to do, I hope that's alright for you?

**Comment by artaban** [comment]
Hi @bentsku, thank you for fixing this

**Review by bentsku — APPROVED** [review]
I'll wait for @cloutierMat to also approve the PR as I did some work, for a quick sanity check, but thank you so much for your contribution @artaban and digging quickly into the code base to fix your own issue! Welcome to the list of LocalStack's contributors!

**Review by cloutierMat — APPROVED** [review]
LGTM! Thanks @artaban for your contribution

**Pull request merged**
