### PR TITLE
transcribe: fix transcription file uri

### PR DESCRIPTION
**Pull request by sannya-singal**
This PR focuses to fix a special case of `TranscriptFileUri` where output key is not null and the file doesn't end with .json. 
The earlier implementation was as per the AWS transcribe docs, but the actual AWS behaviour was different. 

FYI: we are currently skipping the check for `TranscriptFileUri` in all the test cases of transcribe due to other parity issues in the service. 

This will fix a part of #8089.

### CODE REVIEW

**Comment by viren-nadkarni** [comment]
@sannya-singal: Did we ever hear back from AWS on this discrepancy between their docs and implementation?

**Comment by sannya-singal** [comment]
> @sannya-singal: Did we ever hear back from AWS on this discrepancy between their docs and implementation?

I still had to triage and confirm a couple of things earlier before shooting them an email. Did the required investigations today. Planning to send them a message tomorrow with proper data that we have now @viren-nadkarni.

**Comment by sannya-singal** [comment]
> LGTM 👍
> 
> Also consider adding a note to our transcribe docs

About the skipped check for `TranscriptFileUri`? @viren-nadkarni

**Comment by viren-nadkarni** [comment]
> > LGTM 👍
> > Also consider adding a note to our transcribe docs
> 
> About the skipped check for `TranscriptFileUri`? @viren-nadkarni

That LS follows actual AWS behaviour and not what AWS docs say.

**Pull request merged**
