### PR TITLE
Migration to pytest.

### LINKED ISSUE #4007: nose is unmaintained and will stop working with Python 3.10
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

https://github.com/nose-devs/nose/issues/1099 . Nose is unmaintained and it will stop working in Python 3.10 . It will be good to migrate to pytest . There https://github.com/pytest-dev/nose2pytest maintained by pytest devs that helps with migration.

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #4007

### CODE REVIEW

**Comment by tirkarthi** [comment]
It seems for some reason the localstack service is not started before the tests to be executed.

**Comment by tirkarthi** [comment]
Ok, it seems setup_package from nose is used to start services which needs to be ported to pytest : https://stackoverflow.com/questions/52365106/migrating-form-noses-setup-package-to-pytest

**Comment by tirkarthi** [comment]
I can see a kinesis related test failure but I am not sure if it's related to this PR changes.

**Comment by whummer** [comment]
Thanks a lot for digging into this @tirkarthi ! Really great idea to add support for pytest, going forward.

It seems that there are currently 2 issues remaining. The first one is a `None` pointer when using the `inspect` library for reflection: 
```
  File "/home/circleci/project/localstack/utils/kinesis/kinesis_util.py", line 48, in handle_connection
    method_args = inspect.getargspec(self.callback)[0]
```
The second one is related to incorrect format of records being returned - can we try to print the `events` variable below, to help debug this further?
```
        events = get_lambda_log_events(function_name)
>       self.assertEqual(len(events[0]['Records']), 10)
E       TypeError: string indices must be integers
```
Thanks!

**Comment by tirkarthi** [comment]
It seems `listener_func` was not passed which in turn passed None (default) to the underlying functions that used as callback. I just added a simple function that prints similar to others in tests with https://github.com/localstack/localstack/pull/4008/commits/bc46a7f4ee8422abe49c509183a3c0e6c5703ee6#diff-1efd000939c6764bd6df5046c3551419023ae39edfcbb3a3860e7aa6bbbf70feR709 . With that tests pass and the PR can be reviewed. I will try to make a cleanup to PR and remove further references to nose if any.

**Comment by tirkarthi** [comment]
There is an s3 related test failure but I am not sure if it's related to this PR as it seems to occur in only docker and seems to do some batch calls of high number.

**Comment by thrau** [comment]
any updates @tirkarthi ? otherwise i'm happy to finish up the PR

**Comment by thrau** [comment]
i've squashed @tirkarthi 's changes and added my own to https://github.com/localstack/localstack/tree/migrate-pytest

closing this PR and opening a new one from the localstack repo branch. i don't feel comfortable pushing into your fork without consent.

**Comment by tirkarthi** [comment]
Thanks @thrau . I will be away from computer for 2 weeks. Feel free to use the patch as needed. Thanks.

**Pull request closed without merging**
