### PR TITLE
fix clouformation ec2 tests for `ap-northeast-1` and validate against AWS

### PR DESCRIPTION
**Pull request by sannya-singal**
## Motivation
Test `test_vpc_creates_default_sg` and `test_transit_gateway_attachment`fail when run in the [workflow](https://app.circleci.com/pipelines/github/localstack/localstack/23755/workflows/5d782a03-6bc1-4bd2-bcad-c6f1170e5381/jobs/194931/tests) for region: `ap-northeast-1` and throws a `StackDeployError`. 

## Changes
This PR validates test: `test_vpc_creates_default_sg` against AWS and deploys both the tests specifically in `us-east-1`.

### CODE REVIEW

**Comment by sannya-singal** [comment]
we need to update the region values in: `moto.ec2.models.availability_zones_and_regions.RegionsAndZonesBackend`.

**Review by Morijarti — APPROVED** [review]
LGTM as not to block pipeline.
However after adding missing subnet to moto, we should revert these changes

```
"ap-northeast-1": [
            Zone(
                region_name="ap-northeast-1",
                name="ap-northeast-1a",
                zone_id="apne1-az4",
            ),
            Zone(
                region_name="ap-northeast-1",
                name="ap-northeast-1c",
                zone_id="apne1-az1",
            ),
            Zone(
                region_name="ap-northeast-1",
                name="ap-northeast-1d",
                zone_id="apne1-az2",
            ),
        ],
```
in `moto/ec2/models/availability_zones_and_regions.py:143`

**Comment by sannya-singal** [comment]
when we check the availability zones for `ap-northeast-1` on aws, we get the following: 

```
{
    "AvailabilityZones": [
        {
            "State": "available",
            "OptInStatus": "opt-in-not-required",
            "Messages": [],
            "RegionName": "ap-northeast-1",
            "ZoneName": "ap-northeast-1a",
            "ZoneId": "apne1-az4",
            "GroupName": "ap-northeast-1",
            "NetworkBorderGroup": "ap-northeast-1",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "OptInStatus": "opt-in-not-required",
            "Messages": [],
            "RegionName": "ap-northeast-1",
            "ZoneName": "ap-northeast-1c",
            "ZoneId": "apne1-az1",
            "GroupName": "ap-northeast-1",
            "NetworkBorderGroup": "ap-northeast-1",
            "ZoneType": "availability-zone"
        },
        {
            "State": "available",
            "OptInStatus": "opt-in-not-required",
            "Messages": [],
            "RegionName": "ap-northeast-1",
            "ZoneName": "ap-northeast-1d",
            "ZoneId": "apne1-az2",
            "GroupName": "ap-northeast-1",
            "NetworkBorderGroup": "ap-northeast-1",
            "ZoneType": "availability-zone"
        }
    ]
}
```
@Morijarti

**Comment by sannya-singal** [comment]
another fix for this could be selecting 1c instead [here](https://github.com/localstack/localstack/pull/10563/files#diff-04553828ba1af8f05ce7a58840713cc24d18947c3175962aa58ee41846a61972L63), what do you think @Morijarti

**Comment by Morijarti** [comment]
It would fix it in this case, but I think then that the real issue is in how `Fn::GetAZs` works. Let me give it a look @sannya-singal

**Comment by pinzon** [comment]
I'm with @Morijarti probably it would be best if you just extend the functionality of Fn::GetAZs instead of limiting the tests just to force `us-east-1` in the test.

**Comment by sannya-singal** [comment]
> I'm with @Morijarti probably it would be best if you just extend the functionality of Fn::GetAZs instead of limiting the test just to force `us-east-1` in the test.

Hey @pinzon! Thanks for the review. I and @Morijarti had a discussion today regarding the root cause of the issue. For now this has been marked approved to unblock https://github.com/localstack/localstack/pull/10546 and created a backlog item for this.

**Pull request merged**
