### PR TITLE
[6428] fix treating string as JSON array

### PR DESCRIPTION
**Pull request by artkonr**
ref to PR #6428

### CODE REVIEW

**Comment by artkonr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dfangl** [comment]
Hi! First of all, thanks for the contribution.
While this looks good in principal, it seems podman and docker have different output formats here anyway.
For me: `docker ps --format "{{json .}}"` returns one line per container, with the information about each container rendered as json.
`podman ps --format "{{json .}}"` will return a json array, with each container being described by a json dict in a list (love it).

I haven't checked using `podman-docker` yet though, but can you confirm this behavior? If so, this change might not be sufficient for the command to work properly, this would only fix the case where no other container is running.

**Comment by artkonr** [comment]
Greetings @dfangl , thanks for taking a look. 

I knew it's not going to be that simple 👍  It looks like there's no package-manager installation of `podman-docker` on my system, but I'll see if I can do smth about it.

**Comment by thrau** [comment]
Thanks for the effort Artem @artkonr! This is now superseded by #6508

**Pull request closed without merging**
