### PR TITLE
Allow asterisk only wild card

### LINKED ISSUE #8566: bug: MessageAttributes inconsistency on SQS Receive message
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using AWS SDK V3 for JS/TS

localstack

```js
  const { Messages } = await sqsClient.send(new ReceiveMessageCommand({
    QueueUrl,
    MessageAttributeNames: ['*'],
  }));

  console.log(Messages[0].MessageAttributes)
```

it will **not** retrieve the attributes, replacing the astrix with "All" will work
same code will work with real SQS in both cases

Same for aws cli

```shell
> aws --endpoint-url=http://localhost:4566 sqs receive-message --queue-url http://localhost:4566/000000000000/test-queue --max-number-of-messages 1 --message-attribute-names *

{
    "Messages": [
        {
            "MessageId": "99bad5bf-75f6-48b8-ab97-889e679c5a04",
            "ReceiptHandle": "ZTVlNGE2NjAtMDllZC00N2YxLWI4ODItYzUzMzkwZWUyYTA3IGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6dGVzdC1xdWV1ZTEgOTliYWQ1YmYtNzVmNi00OGI4LWFiOTctODg5ZTY3OWM1YTA0IDE2ODc3MDM2NTkuOTgyNTA2",
            "MD5OfBody": "098f6bcd4621d373cade4e832627b4f6",
            "Body": "test"
        }
    ]
}

> aws --endpoint-url=http://localhost:4566 sqs receive-message --queue-url http://localhost:4566/000000000000/test-queue --max-number-of-messages 1 --message-attribute-names All

{
    "Messages": [
        {
            "MessageId": "73cbe585-70a3-4966-99c2-4d4cdf12f095",
            "ReceiptHandle": "Y2M0ZjAwNDAtYTY5MS00MjY5LTkwMmQtNDU4NzBmYzBiYzgxIGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6dGVzdC1xdWV1ZTEgNzNjYmU1ODUtNzBhMy00OTY2LTk5YzItNGQ0Y2RmMTJmMDk1IDE2ODc3MDM2NjMuODcyNzg4",
            "MD5OfBody": "098f6bcd4621d373cade4e832627b4f6",
            "Body": "test",
            "MD5OfMessageAttributes": "f92843aa316e790fb678e5e4ed34d80f",
            "MessageAttributes": {
                "my-test": {
                    "StringValue": "test-value",
                    "DataType": "String"
                }
            }
        }
    ]
}
```

### Expected Behavior

Respect the astrix and behave as as "All"

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run -p 127.0.0.1:4566:4566/tcp --network=host localstack/localstack:2.1.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

CLI

```
aws --endpoint-url=http://localhost:4566 sqs receive-message --queue-url http://localhost:4566/000000000000/test-queue --max-number-of-messages 1 --message-attribute-names *
```

SDK

```js
const { Messages } = await sqsClient.send(new ReceiveMessageCommand({
    QueueUrl,
    MessageAttributeNames: ['*'],
  }));
  ```

### Environment

```markdown
- LocalStack: 2.1.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by fatal10110**
closes #8566 

Just a small note, according to the docs
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#SQS-ReceiveMessage-request-MessageAttributeNames

only `All` and `.*` are allowed as wild card, but actually it also supports `*` (as described in the issue)

### CODE REVIEW

**Comment by fatal10110** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by artur-ma** [comment]
will fix the test later today

**Comment by baermat** [comment]
Hi @fatal10110 , thank you for the contribution, and sorry for the delay!
This looks good, we only need to fix the failing tests. This is caused by the modified test not matching our snapshot, which is  fixable, but requires running the test against live AWS once and can be a bit daunting the first time. All details for how our parity tests work can be found [here](https://docs.localstack.cloud/contributing/parity-testing/).
Alternatively, you can simply copy paste the necessary changes into the json directly. I took the liberty of capturing the necessary snapshot if you prefer it this way.

Steps for direct copying:
1. Find https://github.com/localstack/localstack/blob/master/tests/integration/test_sqs.snapshot.json locally.
2. Exchange the [whole item](https://github.com/localstack/localstack/blob/master/tests/integration/test_sqs.snapshot.json#L2-L160) for "tests/integration/test_sqs.py::TestSqsProvider::test_receive_message_message_attribute_names_filters" with the following code:
```
"tests/integration/test_sqs.py::TestSqsProvider::test_receive_message_message_attribute_names_filters": {
    "recorded-date": "06-07-2023, 11:20:02",
    "recorded-content": {
      "send_message_response": {
        "MD5OfMessageAttributes": "4c360f3fdafd970e05fae2f149d997f5",
        "MD5OfMessageBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
        "MessageId": "<uuid:1>",
        "ResponseMetadata": {
          "HTTPHeaders": {},
          "HTTPStatusCode": 200
        }
      },
      "empty_filter": {
        "Messages": [
          {
            "Body": "msg",
            "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
            "MessageId": "<uuid:1>",
            "ReceiptHandle": "<receipt-handle:1>"
          }
        ],
        "ResponseMetadata": {
          "HTTPHeaders": {},
          "HTTPStatusCode": 200
        }
      },
      "all_name": {
        "Messages": [
          {
            "Body": "msg",
            "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
            "MD5OfMessageAttributes": "4c360f3fdafd970e05fae2f149d997f5",
            "MessageAttributes": {
              "General": {
                "DataType": "String",
                "StringValue": "Kenobi"
              },
              "Hello": {
                "DataType": "String",
                "StringValue": "There"
              },
              "Help.Me": {
                "DataType": "String",
                "StringValue": "Me"
              }
            },
            "MessageId": "<uuid:1>",
            "ReceiptHandle": "<receipt-handle:2>"
          }
        ],
        "ResponseMetadata": {
          "HTTPHeaders": {},
          "HTTPStatusCode": 200
        }
      },
      "all_wildcard_asterisk": {
        "Body": "msg",
        "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
        "MD5OfMessageAttributes": "4c360f3fdafd970e05fae2f149d997f5",
        "MessageAttributes": {
          "General": {
            "DataType": "String",
            "StringValue": "Kenobi"
          },
          "Hello": {
            "DataType": "String",
            "StringValue": "There"
          },
          "Help.Me": {
            "DataType": "String",
            "StringValue": "Me"
          }
        },
        "MessageId": "<uuid:1>",
        "ReceiptHandle": "<receipt-handle:3>"
      },
      "all_wildcard": {
        "Body": "msg",
        "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
        "MD5OfMessageAttributes": "4c360f3fdafd970e05fae2f149d997f5",
        "MessageAttributes": {
          "General": {
            "DataType": "String",
            "StringValue": "Kenobi"
          },
          "Hello": {
            "DataType": "String",
            "StringValue": "There"
          },
          "Help.Me": {
            "DataType": "String",
            "StringValue": "Me"
          }
        },
        "MessageId": "<uuid:1>",
        "ReceiptHandle": "<receipt-handle:4>"
      },
      "only_non_existing_names": {
        "Body": "msg",
        "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
        "MessageId": "<uuid:1>",
        "ReceiptHandle": "<receipt-handle:5>"
      },
      "only_existing": {
        "Body": "msg",
        "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
        "MD5OfMessageAttributes": "fca026605781cb4126a1e9044df24232",
        "MessageAttributes": {
          "General": {
            "DataType": "String",
            "StringValue": "Kenobi"
          },
          "Hello": {
            "DataType": "String",
            "StringValue": "There"
          }
        },
        "MessageId": "<uuid:1>",
        "ReceiptHandle": "<receipt-handle:6>"
      },
      "existing_and_non_existing": {
        "Body": "msg",
        "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
        "MD5OfMessageAttributes": "a311262e065454b75da111d535b8dacd",
        "MessageAttributes": {
          "Hello": {
            "DataType": "String",
            "StringValue": "There"
          }
        },
        "MessageId": "<uuid:1>",
        "ReceiptHandle": "<receipt-handle:7>"
      },
      "prefix_filter": {
        "Body": "msg",
        "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
        "MD5OfMessageAttributes": "83fee93c1bcd8b9a5a923ffacdc636c7",
        "MessageAttributes": {
          "Hello": {
            "DataType": "String",
            "StringValue": "There"
          },
          "Help.Me": {
            "DataType": "String",
            "StringValue": "Me"
          }
        },
        "MessageId": "<uuid:1>",
        "ReceiptHandle": "<receipt-handle:8>"
      },
      "illegal_name_1": {
        "Messages": [
          {
            "Body": "msg",
            "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
            "MessageId": "<uuid:1>",
            "ReceiptHandle": "<receipt-handle:9>"
          }
        ],
        "ResponseMetadata": {
          "HTTPHeaders": {},
          "HTTPStatusCode": 200
        }
      },
      "illegal_name_2": {
        "Messages": [
          {
            "Body": "msg",
            "MD5OfBody": "6e2baaf3b97dbeef01c0043275f9a0e7",
            "MessageId": "<uuid:1>",
            "ReceiptHandle": "<receipt-handle:10>"
          }
        ],
        "ResponseMetadata": {
          "HTTPHeaders": {},
          "HTTPStatusCode": 200
        }
      }
    }
  },
  
```
3. Run the test locally to confirm that no errors happened during the transferal of the data.
If you have any questions or need help, please let me know!

**Comment by baermat** [comment]
I took the liberty of pushing the change. Thank you again for your contribution!

**Pull request merged**
