### PR TITLE
fix(providers): Removed cloudcontrol provider

### PR DESCRIPTION
**Pull request by Pive01**
## Motivation
Removed cloudcontrol provider for community as we moved it in pro

## Changes

Removed cloudcontrol  from the list of community providers

### CODE REVIEW

**Review by silv-io — APPROVED** [review]
Is the code in `localstack.services.cloudcontrol.provider` also migrated to PRO?

If yes, then it's alright. Otherwise we'd have to take a look at that as well before merging

**Comment by Pive01** [comment]
> Is the code in `localstack.services.cloudcontrol.provider` also migrated to PRO?
> 
> If yes, then it's alright. Otherwise we'd have to take a look at that as well before merging

Yes, everything has been moved [here](https://github.com/localstack/localstack-ext/pull/3699)

**Comment by silv-io** [comment]
> > Is the code in `localstack.services.cloudcontrol.provider` also migrated to PRO?
> > If yes, then it's alright. Otherwise we'd have to take a look at that as well before merging
> 
> Yes, everything has been moved [here](https://github.com/localstack/localstack-ext/pull/3699)

In that PR I can only see it being added to pro, but where was that removed from community?

**Comment by Pive01** [comment]
> > > Is the code in `localstack.services.cloudcontrol.provider` also migrated to PRO?
> > > If yes, then it's alright. Otherwise we'd have to take a look at that as well before merging
> > 
> > 
> > Yes, everything has been moved [here](https://github.com/localstack/localstack-ext/pull/3699)
> 
> In that PR I can only see it being added to pro, but where was that removed from community?

Was never added in the first time, initially was [added](https://github.com/localstack/localstack/pull/11830) but half way through we moved it

**Review by simonrw — APPROVED** [review]

**Pull request merged**
