### PR TITLE
Add app://. to the ALLOWED_CORS_ORIGINS for Commandeer

### PR DESCRIPTION
**Pull request by bwship**
Commandeer makes calls to LocalStack with app://. as the CORS header. The workaround until now is to add this in the EXTRA_CORS_ALLOW_ORIGINS environment variable when starting up LocalStack as documented here https://docs.getcommandeer.com/docs/LocalStack/localstack-cors-issues/.

By adding this directly into LocalStack, users of Commandeer will not have to restart their already running LocalStack instance, or specify this when starting up a new instance.

### CODE REVIEW

**Comment by bwship** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by bwship** [comment]
recheck

**Comment by whummer** [comment]
Thanks for this PR @bwship - looks like there are a few changes in the PR of files that are already on `master`. Can you please try rebasing your branch onto latest `master`, to ensure we only see the diff of the changes you've made..? Thanks

**Comment by bwship** [comment]
@whummer - well I tried the rebase.  now this thing has everyone's changes in it - def. not the intention.  Let me know how you think we can proceed.  I might need to close this pr and send out another one.

**Comment by thrau** [comment]
hey @bwship, it looks like you are committing something into `etc/localstack/...` which doesn't look right. have you maybe moved something around in your fork?
maybe it would be easier to start from scratch from the current master.

**Comment by bwship** [comment]
Yea, let me start from scratch. I did a rebase on this one, and it blew up
everything on my end it seems.  You can close out this one, I will create a
new one.  it was a very trivial change.

Cheers,
Bob Wall

(703) 919-3750

**Pull request closed without merging**
