### PR TITLE
Adding support for .NET Core 2.0 Lambda's

### PR DESCRIPTION
**Pull request by hartmannr76**
Went through `lambci`'s documentation to figure out how things should be used and invoked. Confirmed this by using some of the [example Lambda code](https://github.com/lambci/docker-lambda/tree/master/examples/dotnetcore2.0) in the `lambci` repo.

Checklist below of what was needed

- [x] *Add tests for any new features and bug fixes. Ideally, each PR should increase the test coverage.*
- [x] *Follow the existing code style (e.g., indents). A PEP8 code linting target is included in the Makefile.* I'll clean up
- [X] *Put a reasonable amount of comments into the code.* It was fairly straightforward but sure
- [X] *Separate unrelated changes into multiple pull requests.* One feature
- [ ] *1 commit per PR: Please squash/rebase multiple commits into one single commit (to keep the history clean)* (Will do on merge)

### CODE REVIEW

**Comment by hartmannr76** [comment]
Ah, so I just had a bum input for my lambda function. The empty lambda template gives a signature of :
`public string Function(string input, ILambdaContext context)` and I kept getting serialization issues.
After changing it to:
`public string Function(Stream input, ILambdaContext context)` for a string input
Or
```c#
public class Foobar {
   public string foo { get; set; }
}
public string Function(Foobar input, ILambdaContext context)
```
For a serialized JSON input, this worked beautifully

**Comment by hartmannr76** [comment]
So I'd like to add integration tests similarly to the JavaScript and Java ones. I say similarly because ideally the tests just use a precompiled `.dll` file (like the Java tests that pull a JAR) and _just_ run in the docker support (like Node).

The .NET Core packages would likely need to stay in a zip because there are multiple `.dll`'s that come with it. I can include multiple handlers (dynamo events, kinesis, simple stream, etc.) but still need a place to upload the compiled zip.

For now, I'm assuming I can just put them in the lambda folder (raw sample code as well as the zip) but I just want to make sure the maintainers are OK with this.

Any input would be super helpful. I'd also be happy to chat offline

**Comment by whummer** [comment]
Thanks for this PR @hartmannr76 , great to see support for .Net Core Lambdas!

> For now, I'm assuming I can just put them in the lambda folder

Generally it's ok to put test resources into the lambda folder - the only thing I'm concerned about is file sizes. How big are the `.dll` files we're talking about here?

**Comment by hartmannr76** [comment]
So one thing I can do is just include the zipped assets. There are only a handful of additional `.dll`'s and a simple lambda's zip size is ~600kb.
I'd be concerned about losing source context so another option is to include the code next to the zip, incase someone in the future wants to add additional cases to the lambda
```
/lambdas
    /dotnetcore2
        zipped.zip
        DotNetLambda.cs
        DotNetLambda.csproj
        aws-lambda-tools-defaults.json
```
This way it wouldn't need to be recompiled with each build as CI could just reference the zip, but allows context to be kept for what currently is there

**Comment by hartmannr76** [comment]
@whummer Lemme know your thoughts on this approach. Looks like everything is working 😄

**Comment by whummer** [comment]
Merged. Thanks again for following up and polishing the PR @hartmannr76 !

**Pull request merged**
