### PR TITLE
chore(SSL): added persistance for an personal SSL certificats and add…

### PR DESCRIPTION
**Pull request by gpkfr**
* just permit to use own ssl cert without Random (S3)

* add cache-control header to cors

### CODE REVIEW

**Comment by gpkfr** [comment]
#1016 

Yes, off course ;)

[doc]
If you need to use your own SSL Certificate (persistent and not the random one) , you can place into the localstack temporary directory : 

```
/tmp/localstack/
```
the three named file below :

```bash
server.test.pem
server.test.pem.crt
server.test.pem.key
```

- server.test.pem must contains your key file content, your certificat and chain certificate files contents (do a cat in this order)
 - server.test.pem.crt must contains your crt and chains files contents (do a 'cat' in this order)
- server.test.pem.key must contains your key file content

***
Typically with docker-compose you can add into docker-compose.yml this volume to the localstack services :
***
```
volumes:
      - "${PWD}/ls_tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

local directory **ls_tmp** must contains the three files (server.test.pem, server.test.pem.crt, server.test.pem.key)

[/doc]

Hope it can help.
Regards

**Comment by whummer** [comment]
Great, thanks @gpkfr . Can we add this documentation section directly to the `README` file as part of this PR? thx

**Comment by gpkfr** [comment]
Yes, you can.
Best regards,

**Comment by whummer** [comment]
> Yes, you can.

Sorry, when I said "we", I actually meant "you" :) - asking whether you could update this pull request. But nevermind, we can update the README in a follow-up PR. 👍

**Pull request merged**
