### PR TITLE
Set the INTERNAL_AWS_ACCESS_KEY_ID in the header when replaying a non HMAC request.

### PR DESCRIPTION
**Pull request by dmarkey**
This fixes https://github.com/localstack/localstack/issues/4010

### CODE REVIEW

**Comment by whummer** [comment]
Looks great, thanks a lot for digging into this issue @dmarkey ! 👍

**Comment by dmarkey** [comment]
No probs. Great project, happy to contribute. Would you have an idea when a release will be cut with this fix?

**Comment by whummer** [comment]
@dmarkey The change is already available in the `latest` Docker image. We'll cut over a new tagged version shortly (by early next week). Thanks!

**Comment by dmarkey** [comment]
Sweet. So you know the master build broke so not sure if the docker image got updated.

**Pull request merged**
