### PR TITLE
Allow using amazon-maintained lambda docker image repo

### PR DESCRIPTION
**Pull request by isaac-j-miller**
**Please refer to the contribution guidelines in the README when submitting PRs.**
- maps runtime name to image name/version in amazon docker image repo
- writes tests for this mapping

### CODE REVIEW

**Comment by isaac-j-miller** [comment]
Hi,

On my end, it says that for a first time contributor, an admin has to
approve CI builds, so I think that may be the issue.

Thanks,

Isaac

**Comment by whummer** [comment]
> On my end, it says that for a first time contributor, an admin has to
approve CI builds

We did that, actually. Can you please give me push access to your fork/branch? Perhaps it helps if I push a dummy commit to your branch.. Thanks

**Comment by isaac-j-miller** [comment]
Ok, I just now added you as a collaborator on my fork

**Comment by whummer** [comment]
Done! Builds running now.. Actually, I had to do a `git rebase master` and resolve a few minor merge conflicts to get the latest version. Hope you won't run into merge conflicts when pulling the branch (otherwise checking out a fresh copy of the branch may help). Thanks

**Comment by whummer** [comment]
Ok great @isaac-j-miller , looks like the build was triggered this time. 👍  https://app.circleci.com/pipelines/github/localstack/localstack/2070/workflows/78be3800-04f9-4a53-8823-d54d507628c5/jobs/7682

There's a few minor issues with the code linter - can you please take a look? You can replicate this via `make lint` (or `make format` to auto-correct the formatting). Thanks

**Comment by navels** [comment]
Where is this PR at?

**Comment by whummer** [comment]
Thanks @navels , apologies for the delay on this one - we are still in the process of spec'ing out the solution that most suitably fits the internals of our Lambda implementation. Ultimately, I think we'd want to get the official AWS images integrated into LocalStack (even though the work by @mLupine on arm64 support for lambdci is _awesome_! 🙏 ). ARM64 support will be critical, as we've recently released [multi-arch builds](https://github.com/localstack/localstack/issues/4921) to support, e.g., Apple M1.

The main question we are evaluating is whether we want to rely (1) solely on the "over-the-network" invocations required by the AWS Lambda Runtime Interface Client (RIC), or (2) also enable the Docker "entrypoint-based" invocations that Lambci has introduced (i.e., starting up an emphemeral Lambda container that serves only a single request). 

For the former, we could build upon our learnings from the "stay-open" invocation mode for the `docker-reuse` Lambda executor that was [recently merged](https://github.com/localstack/localstack/pull/4914).

For the latter, the advantage is that all communication is only happening in the local context of the Lambda container (the event payload being passed in via `stdin` or as an environment variable to the container) and does not rely on connectivity between the LocalStack container and the Lambda container.

(Arguably, one could prescribe that proper connectivity between LocalStack and the Lambda containers is a prerequisite, but we're seeing a lot of users who are struggling with the networking setup in docker/docker-compose (or even with Helm/Kubernetes) - hence the "entrypoint-based" invocations do actually provide some benefit. From an initial analysis, we should be able to get the "entrypoint-based" invocations working with the official AWS images as well - but we'll see..)

We'll prioritize this work item and will provide an update in the next couple of days.. Thanks!

**Comment by DavidTanner** [comment]
With Nodejs 16.x hopefully coming soon, has there been any movement on switching off of lambci?  

Also, with the throttling changes that have been made to DockerHub, would it be possible to use the public ECR versions?  https://gallery.ecr.aws/lambda/

**Comment by navels** [comment]
Any updates to share?

**Comment by dfangl** [comment]
Hi there! We are definitely working on it! We are trying to do it right, but this might take a couple more weeks. Stay tuned for more updates soon!

**Comment by isaac-j-miller** [comment]
Hi, any update on this?

**Comment by dfangl** [comment]
Yes, I can provide you with an update. We have a prototype of a new lambda engine already merged (see #5306 ). It is based on the official AWS images and shows a huge performance improvements (cold invocation times of around 400-600 ms, hot invocation of around 5ms for simple lambdas, like an echo). Its already merged to master, and can be activated by the instructions in the PR.
However, since we want to make it right, currently there are efforts regarding testing to enable better parity. Therefore, its only a prototype, basically only create / invoke / delete works, as of now. Also, no integrations with other services. and we only tested python and node as of now. Still, we want this to change soon and get traction, once we are done with the work on the tests.

**Comment by dfangl** [comment]
Hi! As explained in my former post, this is now part of a complete Lambda rework. Just exchanging the images will not work like this, but needs more work behind it (see #5306 for our approach to this).
The rework is not abandoned, but temporarily postponed, since other aspects took precedence now.
I will now close this PR. As long as we are not promoting the new provider to default, we will continue supporting new managed runtimes were possible with the docker lambda images of @mLupine (or our own, where necessary), as they integrate seemlessly into the current provider.
Once the work on the new one is finished, we will use the official images like requested.

Still, I want to thank you for your contribution (which also kickstarted the lambda project), they are always very welcome!

**Pull request closed without merging**
