### PR TITLE
chore: update base image to python:3.10.10-slim-bullseye

### PR DESCRIPTION
**Pull request by Mins**
WIP upgrade the base image in Dockerfile to Debian Bullseye

### CODE REVIEW

**Comment by Mins** [comment]
The container image builds are currently failing when installing `timescaledb` using `localstack.cli.lpm`. I'm not really familiar with the packaging system, but it seems to be a private (localstack-ext?). 

@alexrashed do you happen to know how that package can be updated?

**Comment by alexrashed** [comment]
Hi @Mins!
Thanks for your contribution! You are correct, timescaledb is used for our Pro extensions. Unfortunately, this will not allow to upgrade to the latest version of Debian so easily. I'm afraid we will stick to old-stable for a bit (bot not too long). Also, the Dockerfile and the package structure will be quite heavily refactored in a few days (we are currently working towards our next major release).
Is there a reason why you need to use Bullseye instead of Buster right now?

**Comment by Mins** [comment]
Thanks for the clarification @alexrashed ! Our organization has a policy of using only container images with updated base OSes, and the minimum required version for Debian was recently bumped up to Bullseye.

> we will stick to old-stable for a bit (bot not too long).
Since there is already work planned for the upgrade, I'll be happy to close this PR. Can you kindly let me know if there is a rough timeline for the upgrade?

**Comment by alexrashed** [comment]
Sorry I didn't explicitly post an update here earlier. We upgraded to bullseye some time ago with #8344.
LocalStack 2.1.0 is already based on Debian Bullseye (as mentioned [in the release notes](https://github.com/localstack/localstack/releases/tag/v2.1.0))

**Pull request closed without merging**
