### PR TITLE
Add SSM apigateway service test

### PR DESCRIPTION
**Pull request by serialbandicoot**
## Motivation
When attempting to use `uri: arn:aws:apigateway:region:ssm:action/GetParameter` the following error is retuned to the user

```{"Type": "User", "message": "Error invoking integration for API Gateway ID '12345678': API Gateway integration type \"AWS\", method \"GET\", URI \"arn:aws:ssm:region:000000000000:action/GetParameter\" not yet implemented", "__type": "InvalidRequest"}```

As there is no documentation regarding this integration, this test will verify this is currently not available. And when it is this test can be update to reflect the GetParameter on SSM.

## Changes

This is a test only PR.

## Testing

This is a test only PR.

## TODO

What's left to do:

- [ ] Complete the integration of SSM and ApiGateway

### CODE REVIEW

**Comment by serialbandicoot** [comment]
recheck

**Comment by serialbandicoot** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/localstack/localstack/blob/master/.github/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Comment by serialbandicoot** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by samtreweek-bjss** [comment]
Hi @calvernaz - I'm sure you're snowed under! However it would be amazing if you could have a look over this PR and its motivation. I would appreciate the time if you can make some. 😄

**Review by bentsku — CHANGES_REQUESTED** [review]
Hello @serialbandicoot and thanks for your contribution! Sorry for the delay. I believe we should try to write the test against AWS first, and make sure that it runs there. Then, we can `xfail` it against LocalStack as it is not yet implemented as you've found out.

This would greatly help the future implementation of the feature, knowing that this test is the "truth" in what AWS does. Do you think you could update it in that sense?

You can find more informations about contributing in our documentation: https://docs.localstack.cloud/contributing/

And especially this part about validating tests against AWS: https://docs.localstack.cloud/contributing/integration-tests/#test-against-amazon-web-services

**Comment by bentsku** [comment]
Hello @serialbandicoot, circling back to this PR. Are you still interested in updating it to run against AWS to follow our guidelines regarding integration tests? Thanks!

**Comment by bentsku** [comment]
@serialbandicoot thanks again for your contribution, I've taken the liberty to AWS validate the test and push the changes.
As I've done most of the changes, @cloutierMat would mind reviewing as a sanity check? Thanks! 🙏 I'll approve to unblock the merge.

**Review by bentsku — APPROVED** [review]

**Review by cloutierMat — APPROVED** [review]
Awesome! Nice to have an extra test at the ready!

**Pull request merged**
