### PR TITLE
Adding in signal trap support to the docker-entrypoint

### PR DESCRIPTION
**Pull request by zonywhoop**
This PR adds signal trap support for the docker-entrypoint.sh file.  Because we are spinning up supervisord to then load localstack, when Docker sends a sigterm to the container it only sends it to PID 1 which means that signal is never reaching supervisord. Docker will eventually kill off all of the processes, however, depending on the environment and configuration this time can take from a few seconds to a few minutes. Trapping the SIGTERM signal in the docker-entrypoint allows us to then send that signal to supervisord and in turn allows for a clean shutdown of all services and a clean exit of the container.

This change has been tested in a kubernetes environment and resulted in the container consistently terminating 1-2 minutes faster than without it.

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this enhancement @zonywhoop ! We still need to do a bit of testing to see which potential side effects this may have. For example, we have a mechanism to restart the LocalStack process to reload the state from persistence storage. 

Happy to merge this change as-is, we can iterate over it as needed. The only thing - I'm wondering if we should put this change behind a feature flag, e.g., a new environment variable `HANDLE_SIGTERM` that can be used to either enable or disable the new behavior. What do you think?

**Comment by zonywhoop** [comment]
Can you point me to the mechanism being used to reload LocalStack?  So long as the supervisord pid isn't changing (it doesn't matter if the LocalStack pid changes) then everything should work perfectly - but happy to test that to make sure.

I can look into wrapping this in a feature flag too and see what issues that brings up if any.

**Comment by whummer** [comment]
Ok, thanks. Let's merge the PR as-is, and see how it goes - perhaps we can still add a feature flag in a follow-up PR. Thanks

**Comment by whummer** [comment]
Quick heads-up @zonywhoop - as expected, this signal trap seems to be causing issues on some systems - if users hit [CTRL]-[C] on their local machine, then the container does not tear down properly but hangs forever.

We're adding a config flag `SET_TERM_HANDLER` in #3450 that you can use to enable this functionality - please update your kube config correspondingly. Thanks!

**Comment by zonywhoop** [comment]
Gotcha, completely forgot about interactive runs.  We can fix that by capturing `SIGINT` as well and either converting it to `SIGTERM` or just pass it through as `SIGINT`. I'll merge in #3450 and work on adding the other trap for `SIGINT` and run the interactive tests locally to verify and submit a new MR.

**Pull request merged**
