### PR TITLE
Attempting to fix problems associated with issue #259

### PR DESCRIPTION
**Pull request by matt-wormley**
My attempts to clean up my fork inadvertently closed my previous PR. Here are my changes in a single commit.

I also attempted to install default /root/.aws/{config|credentials} files with odd results. The boto3 behavior around this stuff seems very uneven. I think we're on the right track but I haven't time to dig further at this point. It is going to take some experimentation to figure out the right combination here. Thanks!

### CODE REVIEW

**Comment by whummer** [comment]
I've tried building the Docker image locally from your branch, but was running into the following issue when starting up:
```
$ DEBUG=1 localstack start --docker
...
2017-09-01T09:41:51:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-09-01T09:41:54:ERROR:localstack.services.kinesis.kinesis_starter: Kinesis health check failed: You must specify a region. Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 32, in check_kinesis
out = aws_stack.connect_to_service(service_name='kinesis', client=True, env=ENV_DEV).list_streams()
File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 151, in connect_to_service
return method(service_name, region_name=region, endpoint_url=endpoint_url, verify=verify)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
return _get_default_session().client(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/boto3/session.py", line 263, in client
aws_session_token=aws_session_token, config=config)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/session.py", line 836, in create_client
client_config=config, api_version=api_version)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 70, in create_client
verify, credentials, scoped_config, client_config, endpoint_bridge)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 224, in _get_client_args
verify, credentials, scoped_config, client_config, endpoint_bridge)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
endpoint_url, is_secure, scoped_config)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/args.py", line 103, in compute_client_args
service_name, region_name, endpoint_url, is_secure)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 297, in resolve
service_name, region_name)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
partition, service_name, region_name)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
raise NoRegionError()
NoRegionError: You must specify a region.
...
```

As I mentioned on the previous PR, we need to make sure that the container still starts up properly after removing the environment variables. We can achieve that by either
(1) Setting the region and credentials manually in the code (if necessary, i.e., if not configured elsewhere), or
(2) creating default `~/.aws/{credentials,config}` files

You mentioned previously that you had some issues getting version (2) working. Can you please elaborate a bit more which exact issues you've been running into?

I gave it a quick try by adding the following to the Dockerfile:
```
RUN mkdir -p /root/.aws && \
    echo '[default]' > /root/.aws/config && \
    echo 'region = us-east-1' >> /root/.aws/config && \
    echo '[default]' > /root/.aws/credentials && \
    echo 'aws_access_key_id = foo' >> /root/.aws/credentials && \
    echo 'aws_secret_access_key = foo' >> /root/.aws/credentials && \
```
... and it seems to work. The container starts up properly, I can `docker exec` into the running container and run `aws` CLI commands. Also overwriting the config by mounting local files into `~/.aws/{credentials,config}` seems to work. Can you please give it a try, or report the exact error message that you encountered. Thanks!

**Comment by whummer** [comment]
Any updates on this PR @matt-wormley , did you have a chance to build/run the image locally and test the change described above (`RUN ...` in Dockerfile)? Thanks

**Comment by whummer** [comment]
Closing this PR in favor of #389 . Note that your authorship is retained in the other PR. Thanks again.

**Comment by matt-wormley** [comment]
Sorry man - I just haven't been able to get back to this and we have a working image. I know the solution is right there, but it'll just take time to get it worked out. Great project. I look forward to having more time for this in the future.

**Pull request closed without merging**
