### PR TITLE
feat: add tolerated failure count/percentage to SFN map state

### PR DESCRIPTION
**Pull request by u-minor**
## Motivation

Currently the SFN interpreter lacks support for ToleratedFailure* declarations in distributed Map state.
This PR introduces support for these declarations.
Closes: #10056

## Changes

- Added grammar support for `ToleratedFailureCount`, `ToleratedFailureCountPath`, `ToleratedFailurePercentage`, `ToleratedFailurePercentagePath` in the ASL lexser and parser.
- Added new parsing components of these declarations and pass values to MapRunRecord.
- Added relevant test.

### CODE REVIEW

**Comment by u-minor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MEPalma** [comment]
@u-minor Thank you for bringing this forward! We would be happy to merge these changes and address any adjustments in the future. Feel free to rebase your branch with master -- I would also be happy to take of this.

**Comment by u-minor** [comment]
@MEPalma Sorry for the late reply. I will rebase this weekend.

**Comment by u-minor** [comment]
@MEPalma I would like to add Label and ResultWriter to the map state after this PR.
I am ready to create each PR, but if you prefer to include them to this and review them all at once, let me know.

https://github.com/u-minor/localstack/commit/54c9235489c9c6584bc546f134999f926f4efa10

- Label: https://github.com/u-minor/localstack/commit/0ac3c6e13d150aa49f996585cb0a0923217cb20f
- ResultWriter: https://github.com/u-minor/localstack/commit/54c9235489c9c6584bc546f134999f926f4efa10
    > Currently only dummy manifest.json generation is supported

**Pull request merged**
