### PR TITLE
Bind endpoints to access SMS messages sent via SNS

### LINKED ISSUE #7935: feature request: expose endpoint to retrieve SMS messages delivered via SNS
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

SNS allows for the publishing of messages to an SMS destination with a phone number. Those messages are logged and stored in the `SnsStore`, but there is no way to retrieve them for verification. The request here is to expose a new endpoint which returns SMS messages from the store, similar to the one made available to retrieve email messages sent via SES.

### 🧑‍💻 Implementation

The `SNSServicePlatformEndpointMessagesApiResource` class makes endpoints available for accessing platform endpoint messages sent via SNS. A similar resource class could be implemented to provide new endpoints for accessing SMS messages.

Given that interaction platform endpoint messages is exposed at the path `/_aws/sns/platform-endpoint-messages`, SMS message interaction would presumably be exposed at `/_aws/sns/sms-messages`. A `GET` endpoint could accept an optional `phoneNumber` query parameter to filter messages based on the destination phone number.

```python
class SNSServiceSMSMessagesApiResource:
  @route(sns_constants.SMS_MSGS_ENDPOINT, methods=["GET"])
    def on_get(self, request: Request):
      account_id = #...
      region = #...
      filter_phone_number = request.args.get("phoneNumber")
      # get store; conditionally filter messages based on filter_phone_number
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ckolek**
**Please refer to the contribution guidelines in the README when submitting PRs.**

fixes #7935

### CODE REVIEW

**Comment by ckolek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bentsku** [comment]
Hi @ckolek! Thank you for your contribution! Is there anything I could do to help you get this PR over the line?

**Comment by bentsku** [comment]
Hi @ckolek, sorry for pinging you again. Would it be okay if I push commits to your branch to get the CI to pass and we could then merge your PR? Thanks!

**Comment by bentsku** [comment]
As there has not been any activity in 3 months, I've cherry picked your commit with attribution and opened a new PR implementing your feature and added a test. Thanks again for your contribution! 
The PR: #8667

**Pull request closed without merging**
