### PR TITLE
Fix: CORSRule -> CORSRules rename in s3_listener to resolve #3926

### LINKED ISSUE #3926: CORS Rules not Respected because of invalid Key access
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

https://github.com/localstack/localstack/blob/master/localstack/services/s3/s3_listener.py#L340

Is accessing the CORSRules key of the bucket incorrectly

...

## Expected behavior
`rules = cors['CORSConfiguration']['CORSRules']` 
...

## Actual behavior
`rules = cors['CORSConfiguration']['CORSRule']` <--- key is not plural  when it should be

...

# Steps to reproduce

Try any request expecting `access-control-allow-origin` response header to not be `*` when Origins are specified, still get `*` back

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

### PR DESCRIPTION
**Pull request by EfChouTR**
Fix CORSConfiguration nested key access of CORSRules

Resolves #3926

### CODE REVIEW

**Comment by EfChouTR** [comment]
build failed due to push timeout; otherwise container built and started correctly

image

**Comment by whummer** [comment]
Thanks this pull request @EfChouTR ! Looking at the [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketCors.html), I am not sure if this is the right solution to this issue. The request data contains a `CORSRule` element (in singular):
```
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
   <CORSRule>
      <AllowedHeader>string</AllowedHeader>
      ...
```

Can you please share some details about the issue (error message) you're seeing - perhaps we need to change this to something like:
```
     rules = cors['CORSConfiguration'].get('CORSRule') or []
```
?

**Comment by EfChouTR** [comment]
> Thanks this pull request @EfChouTR ! Looking at the [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketCors.html), I am not sure if this is the right solution to this issue. The request data contains a `CORSRule` element (in singular):
> 
> ```
> <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
>    <CORSRule>
>       <AllowedHeader>string</AllowedHeader>
>       ...
> ```
> 
> Can you please share some details about the issue (error message) you're seeing - perhaps we need to change this to something like:
> 
> ```
>      rules = cors['CORSConfiguration'].get('CORSRule') or []
> ```
> 
> ?

@whummer when applying a JSON file to the S3 CORS Policy (`awslocal s3api put-bucket-cors --cli-input-json file://s3.json`) it allows the key as `CORSRules`
If you try it as `CORSRule` (singular) it throws an error saying supported key is `CORSRules`
```
{
	"Bucket": "my-test-bucket",
	"CORSConfiguration": {
		"CORSRules": [
			{
				"AllowedHeaders": [
					"*"
				],
				"AllowedMethods": [
					"PUT",
					"GET"
				],
				"AllowedOrigins": [
					"https://mylocal.domain",
					"https://mylocal.domain:*"
				],
				"ExposeHeaders": [
					"*"
				],
				"MaxAgeSeconds": 3000
			}
		]
	}
}
```

This is in test_s3.py

image

so if the response is XML, you are correct. If the response is JSON then the fix in the PR is correct

**Comment by EfChouTR** [comment]
The error I am seeing is the OPTIONS request returns `Access-Control-Allow-Origin: *` despite having the CORS policy set

This in turn fails the preflight CORS check

**Comment by EfChouTR** [comment]
Closing as this doesnt work after trying locally

**Pull request closed without merging**
