### PR TITLE
use mounts instead of volumes docker api

### PR DESCRIPTION
**Pull request by thrau**
## Motivation

I tried to mount a volume bind with a colon in the name, which fails both for the CLI and SDK docker client. The reason is explained here https://github.com/docker/docker-py/issues/2041

This can be fixed by using the more flexible `mounts` api parameter. 

> mounts is more modern and a better choice 99% of the time.
-- https://github.com/docker/docker-py/issues/2041#issuecomment-393359696

> In general, --mount is more explicit and verbose. The biggest difference is that the -v syntax combines all the options together in one field, while the --mount syntax separates them
-- https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag

This PR changes both the docker SDK and CMD client to use `mounts` instead of `volumes`/`bind` for mounting volumes.
There is a significant impact though: the `-v` flag would create a source directory on the host if it didn't exist, whereas `--mount` would fail. To make sure we don't break code, we explicitly create the directories now, however they will be created as the user that owns the python process (typically the user), rather than the docker process (typically root).

Open to discuss the implications and how we could mitigate them.

## Changes

* Rework the `VolumeBind` mapping to map to `mounts` instead of `volumes`
* If a volume source didn't exist on the host before spawning a container, the owner of the created directory is now the user running localstack and no longer the user running docker (which would typically be `root`)

### CODE REVIEW

**Comment by alexrashed** [comment]
Awesome! It would be great to properly assign permissions to the localstack volume directory! 🦸🏽 
Concerning the impact of this: I haven't dug into the specifics of `mount`, but would this approach work with already exising volumes owned and writable only by `root`?
Otherwise, imho this would be a breaking change. This can be easily fixed by removing the directory, but I guess this should either be a migration instruction in a major release, or it should be done automatically...

**Comment by dfangl** [comment]
I rebase this to get a current test run.

My biggest concern with this is the changed behavior of creating non-existent directories on the host. They are captured in the CLI tests I think. 
Another instance that might be problematic is persistence, where we mount a subfolder of the /var/lib/localstack/state directly into a container. We have to make absolutely sure that that will exist before.

I took a quick look into it, and there might be some logical errors there, preventing this change.

**Comment by dfangl** [comment]
I converted this to draft, as we discussed that there are too many open questions to go forward with it right now.

**Comment by thrau** [comment]
closing this PR since as @dfangl said there are too many issues with it potentially breaking environments.
i would keep this in mind though when developing container abstractions /cc @simonrw. 

perhaps we can also refactor some of the existing code docker client code to more clearly separate "volume" and "mount" terminology in method parameters etc, so we can start introducing mounts as an alternative when creating containers.

**Pull request closed without merging**
