### PR TITLE
Draft: Add object tagging notification support

### PR DESCRIPTION
**Pull request by threewordphrase**
**Please refer to the contribution guidelines in the README when submitting PRs.**

Adds support for s3 object tagging notifications as reported/requested in https://github.com/localstack/localstack/issues/6089

### CODE REVIEW

**Comment by threewordphrase** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by threewordphrase** [comment]
recheck

**Comment by threewordphrase** [comment]
@thrau I'm having CI problems I can't repro locally with my diffs ported to the localstack 0.14.2 container, and I'm also not having any luck getting the repo set up locally to run tests. I've tried `make install-test && make test`, had a missing libsasl2-dev error and fixed that, now I have 
```
  File "/home/asmith/code/localstack-aes/localstack/testing/aws/cloudformation_utils.py", line 9, in <module>
    def load_template_file(file_path: str | os.PathLike, *, path_ctx: str | os.PathLike = None) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'
```
on `make test`... what's the easiest way to just use docker? Host-side python considered harmful and all that

**Comment by thrau** [comment]
that's great progress @threewordphrase, thanks for grinding through the testfailures. the state of S3 is really a bummer at the moment and we'll put in some effort there soon to make the development experience more friendly.

we have a make target here so you can run specific tests in docker https://github.com/localstack/localstack/blob/e2618605481e3c059e15587c34a311b7b482cfe9/Makefile#L183-L188

if you specify `TEST_TARGET=tests/integration/s3/<...> make ...` you can run specific tests rather than the entire test suite.

**Comment by thrau** [comment]
I think i found the issue, i'll push to your branch if that's OK :-) there's also a bucket tagging request where the path looks like this `'/tf-bucket?tagging='`
in which case this line would fail: https://github.com/threewordphrase/localstack/blob/bdfd0899d58404cb5eb6aa80fa9b262dd7ef3853/localstack/services/s3/s3_listener.py#L1441

so we need to first check whether it's a real object request before taking the control path, like we do here: https://github.com/threewordphrase/localstack/blob/bdfd0899d58404cb5eb6aa80fa9b262dd7ef3853/localstack/services/s3/s3_listener.py#L1419-L1424

**Comment by thrau** [comment]
i also rebased and force pushed the branch

**Review by thrau — APPROVED** [review]
LGTM @threewordphrase. tests are green so i think we're good to go!

**Comment by thrau** [comment]
looks like there's a flake left, i'll take a look

**Comment by thrau** [comment]
Thanks a lot for the contribution @threewordphrase !

**Pull request merged**
