### PR TITLE
Remove pytz

### PR DESCRIPTION
**Pull request by viren-nadkarni**
### Summary

Removes dependency on `pytz`. All the functionality that it offered is now included in the standard library.

### Related
https://github.com/spulec/moto/pull/5749

<https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html>

### CODE REVIEW

**Review by thrau — APPROVED** [review]
nice! :100:

**Review by alexrashed — APPROVED** [review]
Awesome, thanks for the cleanup! 🚀

**Review by calvernaz — APPROVED** [review]
Thanks for doing this, LGTM!

**Comment by joe4dev** [comment]
nice cleanup 👍 

@viren-nadkarni Remember to bump moto-ext in `setup.cfg` to fix LS host mode raising the error `No module named 'pytz'` in moto:
`moto-ext[all]==4.0.12.post1` => `moto-ext[all]==4.0.12.post2`

**Pull request merged**
