### PR TITLE
Cleanup replay-based persistence

### PR DESCRIPTION
**Pull request by giograno**
This PR removes the code related to the record/replay-based persistence feature. It impacts [this](https://github.com/localstack/localstack-ext/pull/601).

### CODE REVIEW

**Comment by thrau** [comment]
rebased the branch

**Comment by giograno** [comment]
@thrau integration with pro will fail cause we call some functions that do not exists anymore (see https://github.com/localstack/localstack-ext/pull/601)

**Review by alexrashed — APPROVED** [review]
LGTM!
The only question is if the replay persistence should be removed with v1 or maybe prior to that (because there might be another release before v1).
It has been deprecated for a long time already though, so I'm fine with both.

**Comment by giograno** [comment]
Good point @alexrashed. We already did announce in [0.14.3](https://github.com/localstack/localstack/releases/tag/v0.14.3) that we would have removed it in the next release. I do not have strong opinions about it. What do you think @thrau?

**Review by thrau — APPROVED** [review]
LGTM! let's merge into v1

**Pull request merged**
