### PR TITLE
Rename default container name to localstack-main

### PR DESCRIPTION
**Pull request by simonrw**
## Motivation

Hyphens are not allowed in URLs. When addressing the LocalStack container over a docker network, the container name resolves to the IP address of the container. This is a problem in particular for `boto3` which refuses to connect.

## Changes

Rename `localstack_main` -> `localstack-main`

### CODE REVIEW

**Review by alexrashed — COMMENTED** [review]
The changes are looking good, but I think you have to rebase your PR based on the latest release/v3 branch (we don't automatically trigger rebases of transitive Prs anymore).

**Comment by simonrw** [comment]
> The changes are looking good, but I think you have to rebase your PR based on the latest release/v3 branch (we don't automatically trigger rebases of transitive Prs anymore).

:facepalm: 

(there is no facepalm reaction :()

**Review by alexrashed — APPROVED** [review]
Awesome! It's great to see this change getting over the line! There aren't too many changes necessary, so I think this should be fine, especially if we can prepare our users appropriately and update all our own repos and docs in advance! 🚀 🧹

**Review by joe4dev — APPROVED** [review]
LGTM on the LocalStack side 👍 

There are some more references in other places to sync:
* https://docs.localstack.cloud/references/configuration/
* CircleCI orb (docs appear auto-generated from our repo): https://circleci.com/developer/orbs/orb/localstack/platform
...

**Pull request merged**
