### PR TITLE
Update Elasticsearch to 7.1 [WIP]

### PR DESCRIPTION
**Pull request by quozd**
Updates Elasticsearch to 7.1.
This is the latest supported version by AWS

### CODE REVIEW

**Comment by ScheerMT** [comment]
Any traction on this?

**Comment by quozd** [comment]
@ScheerMT Docker version is ready to use. I need to find some time to finish Python implementation. Should be ready soon.

**Comment by whummer** [comment]
Thanks for this PR @quozd ! With your permission, I'll take over from here and push this one over the line, as this is relatively high prio for us. Will make sure to preserve your original commit, to retain your authorship.

**Comment by whummer** [comment]
Fixed and merged in #2195 - thanks again.

**Pull request closed without merging**
