### PR TITLE
Add test for EventBridge Scheduler TagResource API and UntagResource API

### PR DESCRIPTION
**Pull request by kakakakakku**
## Motivation

Hi😀

I checked the EventBridge Scheduler API coverage and found that some APIs were not marked in the "Internal Test Suite". So I wanted to contribute by adding tests.

- https://docs.localstack.cloud/references/coverage/coverage_scheduler/

## Changes

In this Pull Request, I’ve added a test for the EventBridge Scheduler `TagResource` API and `UntagResource` API to improve coverage.

It's a bit hard to understand, but the `TagResource` API and `UntagResource` API are not for EventBridge Scheduler, It's specifically for EventBridge Scheduler Group.

- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/scheduler/client/tag_resource.html
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/scheduler/client/untag_resource.html

## Testing

The tests passed in my local environment.

```sh
$ make test TEST_PATH=tests/aws/services/scheduler
(snip)
tests/aws/services/scheduler/test_scheduler.py::test_tag_resource PASSED                                                                                                                                                    [ 66%]
tests/aws/services/scheduler/test_scheduler.py::test_untag_resource PASSED                                                                                                                                                  [100%]
```

Could you please review? Thanks a lot 👍

I am also submitting some pull requests. I would appreciate it if you could take a look at that as well. Thanks.

- https://github.com/localstack/localstack/pull/11841
- https://github.com/localstack/localstack/pull/11858

### CODE REVIEW

**Comment by kakakakakku** [comment]
OK, thanks!
I will add snapshot tests shortly 😀

**Comment by maxhoheiser** [comment]
> OK, thanks! I will add snapshot tests shortly 😀

Just added them for you :) feel free to merge once all the tests re green

**Review by maxhoheiser — APPROVED** [review]
Nice small tests 👍 - feel free to merge once all tests are green

**Comment by kakakakakku** [comment]
@maxhoheiser 
Thank you for your support😀
Next time I add tests, I will also use conftest and include snapshot testing.

**Pull request merged**
