### PR TITLE
Remove unused CFn resolving

### PR DESCRIPTION
**Pull request by dominikschubert**
In #7149 (nearly a month ago) this has been disabled by default, since we had the hypothesis that it is actually redundant. We haven't had to make use of the fallback flag since, so it is safe to assume that we can finally remove it.

This PR now cleans up all the resource models by removing the corresponding calls as well as the implementation itself.

### CODE REVIEW

**Review by alexrashed — APPROVED** [review]
Nice! All the changes are looking good to me and are safe. Since CloudFormation is used quite a lot, I think it's fair to assume that the legacy resolving is not necessary anymore after a month. 🚀

**Review by baermat — APPROVED** [review]
LGTM :rocket:

**Review by macnev2013 — APPROVED** [review]
Looks good 👍🏻

**Review by viren-nadkarni — APPROVED** [review]

**Review by whummer — APPROVED** [review]
Looks great, nice cleanup @dominikschubert ! 🚀 🥳  

LGTM - tested the changes with a couple of corner cases, wasn't able to craft up any samples that would create issues with this change. 👍 

For reference, the reason why this change is safe is primarily this line: https://github.com/localstack/localstack/blob/6af793ccd5ccbcf928a7adf342a8f47458a81fb0/localstack/services/cloudformation/engine/template_deployer.py#L1437-L1438

There's a few edge cases with refs which surfaced during testing - e.g., using an undefined reference raises a `ValidationError` on AWS. But this is unrelated to these changes, and we can tackle it separately.. 👍 
```
MyQueue:
  Type: 'AWS::SQS::Queue'
  Properties:
    QueueName: !Sub "test-${undefined}"
```

**Pull request merged**
