### PR TITLE
Update broken links in localstack-concepts/Readme.md

### PR DESCRIPTION
**Pull request by dance-cmdr**
## Motivation

#11819  &  OCD!
I was reading the documentation and I found some broken links. I think they need some love and it will help new joiners.

## Changes

- Updates 5 links to localstack resources that are out of date since the refactoring. 

| Before  | After  |
|--------|--------|
| Screenshot 2024-11-09 at 23 12 32|Screenshot 2024-11-09 at 23 14 42|

## Testing

- [ ] Visit each of the changed links and click them. They should lead you to the correct localstack resource.

### CODE REVIEW

**Comment by dance-cmdr** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by dance-cmdr** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by dance-cmdr** [comment]
> **dance-cmdr** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **CLA Assistant Lite bot**.

New machine and pointing to a new email. That have been rectified in GitHub but we might need to rerun the job.

**Review by HarshCasper — APPROVED** [review]
Thank You!

**Pull request merged**
