### PR TITLE
Add newline after XML preamble in S3 responses for Serverless compatibility

### PR DESCRIPTION
**Pull request by whummer**
Add newline after XML preamble in S3 responses for Serverless compatibility. 

Instead of this:
```
<?xml version="1.0" encoding="UTF-8"?><LocationConstraint ...
```
We need to return:
```
<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint ...
```

Tested against real AWS.

This is required because moto is generally collapsing all S3 XML responses: https://github.com/spulec/moto/blob/3718cde444b3e0117072c29b087237e1787c3a66/moto/core/responses.py#L102-L104 . Without this change, newer versions of Serverless are failing with:
```
Serverless: [AWS cloudformation 400 1.645s 0 retries] describeStacks({ StackName: 'sls-test-local' })
Serverless: Ensuring that deployment bucket exists
Serverless: [AWS s3 200 0.022s 0 retries] getBucketLocation({ Bucket: 'localstack-websockets-serverless' })

 Serverless Error ----------------------------------------

  ServerlessError: Deployment bucket is not in the same region as the lambda function
```

Debugging the Serverless logic a bit more, it turns out that the location constraint gets extracted as the (literal) string `<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">` instead of the location value like `us-east-1` (seems like a bug in their XML parser).

### CODE REVIEW

**Review by thrau — APPROVED** [review]
LGTM! we should probably also write an issue report for serverless. seems pretty silly to depend on newlines when parsing xml ...

**Comment by whummer** [comment]
Interesting! Seems to be caused by an issue in the AWS JS SDK itself.

This example:
```
const AWS = require("aws-sdk");
const client = new AWS.S3({endpoint: "http://s3.localhost.localstack.cloud:4566"});
(async () => {
  await client.createBucket({Bucket: "test"}).promise();
  const result = await client.getBucketLocation({Bucket: "test"}).promise();
  console.log(result);
})();
```
... results in:
```
$  node test.js
{
  LocationConstraint: '<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/">'
}
```
(without the changes in this PR).

**Comment by fabiob** [comment]
Hi! Can this change be impacting `GetObject` responses from S3? My XML files are suddenly receiving this newline after the preamble.

**Comment by whummer** [comment]
Thanks for the pointer @fabiob - mostly likely that was an oversight, so it's quite possible. We'll look into it shortly.. 👍

**Pull request merged**
