### PR TITLE
Migrate from nose test to pytest

### PR DESCRIPTION
**Pull request by thrau**
This PR builds on #4008 and adds a more elaborate starting procedure that we also use in https://github.com/localstack/localstack-terraform-test (i added documentation).

other changes:
* some deprecation warnings in tests
* added a check in the TestTerraform integration test that will skip the test if the terraform command fails
* add pytest plugin that can re-run failed integration tests

### CODE REVIEW

**Comment by thrau** [comment]
build times look good! tests pass! :exploding_head: 

looks like we can get this over the line @whummer :-)

**Comment by whummer** [comment]
Awesome PR - great to see we can get this one over the line. 🎉  Thanks @thrau 👍 , and kudos to @tirkarthi for the initial version of this change!! 🚀

**Review by whummer — APPROVED** [review]

**Comment by whummer** [comment]
Merged - @tirkarthi  we've made sure that your original authorship is retained in the commit history.. Thanks!

**Comment by tirkarthi** [comment]
Thanks @whummer and @thrau

**Pull request merged**
