### PR TITLE
SSM & SecretsManager - Changed date format for SDK compatibility

### PR DESCRIPTION
**Pull request by jellybeat**
Change in dates format to long so the response can be interpreted by SDKs (tested in Java AWS SDK v2)

You can test using the Java SDK v2 with this snippet:

```
import software.amazon.awssdk.services.ssm.*;
import software.amazon.awssdk.services.ssm.model.*;

import java.net.URI;

public class App 
{
    public static void main( String[] args ) {
        SsmClient client = SsmClient.builder().endpointOverride(URI.create("http://localstack:4566")).build();
        GetParametersResponse response = client.getParameters(GetParametersRequest.builder().names("/aws/reference/secretsmanager/test_secret", "/aws/reference/secretsmanager/no_secret","test_parameter", "no_parameter").build());
        System.out.println( response );
    }
}
```

The console prints the following:

```
GetParametersResponse(Parameters=[Parameter(Name=/aws/reference/secretsmanager/test_secret, Type=SecureString, Value=test_secret, LastModifiedDate=2020-11-22T05:10:49Z), Parameter(Name=test_parameter, Value=test_parameter, Version=1, LastModifiedDate=2020-11-22T05:10:50Z, ARN=arn:aws:ssm:us-east-1:1234567890:parameter/test_parameter)], InvalidParameters=[/aws/reference/secretsmanager/no_secret, no_parameter])
```

**NOTE:** This only applies for the AWS SDK Version 2 iterations, it is not compatible with AWS SKD Version 1. Which brings my following question.

**What is the support policy for the wide variety of SDKs and its versions?**
In case of this feature (SSM & SecretsManager integration) the payload needs to be different depending on the Java SDK. The response format used to comply with the Java JDK v2 (`software.amazon.awssdk.services.ssm`) is incompatible with the one used with the Java JDK v1 (`com.amazonaws.services.simplesystemsmanagement`).

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-340) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @jellybeat !

>  In case of this feature (SSM & SecretsManager integration) the payload needs to be different depending on the Java SDK. The response format used to comply with the Java JDK v2 (software.amazon.awssdk.services.ssm) is incompatible with the one used with the Java JDK v1 (com.amazonaws.services.simplesystemsmanagement).

Are you sure about this? If I understand correctly, then the real AWS API would return different values if the request is made from either a v1 or a v2 SDK. I'm not sure if that is the case. Rather, I believe there should be one canonical format that works for both SDKs. Do you think we can add a small test to our [Java utils here](https://github.com/localstack/localstack-java-utils) to help reproduce the behavior with both - v1 and v2 SDKs? (both versions are already integrated into the classpath) Thanks for your help.

**Comment by jellybeat** [comment]
Yes, I still have the Java utils PR pending, I'm working on it when I have time. If there is a canonical format, I'm having a hard time finding it 😓.
At least when using the following artifact:
```
<groupId>com.amazonaws</groupId>
<artifactId>aws-java-sdk-ssm</artifactId>
<version>1.11.398</version>
```
I'm getting the following parsing error:
```
Caused by: java.lang.RuntimeException: We expected a VALUE token but got: START_OBJECT
  at com.amazonaws.transform.JsonUnmarshallerContextImpl.readCurrentJsonTokenValue(JsonUnmarshallerContextImpl.java:152)
  at com.amazonaws.transform.JsonUnmarshallerContextImpl.readText(JsonUnmarshallerContextImpl.java:135)
  at com.amazonaws.transform.SimpleTypeJsonUnmarshallers$StringJsonUnmarshaller.unmarshall(SimpleTypeJsonUnmarshallers.java:34)
  at com.amazonaws.transform.SimpleTypeJsonUnmarshallers$StringJsonUnmarshaller.unmarshall(SimpleTypeJsonUnmarshallers.java:32)
...
```
I still need to dig deeper, but because of the `We expected a VALUE token but got: START_OBJECT` message my impression is that SDK version is not expecting a nested format in the secret when perfoming the get-params call. I base this on how the old aws-cli (`1.14.5`) formats the result.

Here is what I mean:
1)Fire up the latest version of localstack
2)Create a secret and a param:
```
aws --endpoint-url http://localstack:4566 secretsmanager create-secret --name test_secret --secret-string 'test_secret' && \
aws --endpoint-url http://localstack:4566 ssm put-parameter --name test_parameter --value 'test_parameter'
```
3)Make a ssm get-params request with AWS CLI 1.14.5
Request
```
aws --version
aws-cli/1.14.5 Python/2.7.13 Linux/5.4.39-linuxkit botocore/1.8.9

aws --endpoint-url http://localstack:4566 ssm get-parameters \
    --names /aws/reference/secretsmanager/test_secret /aws/reference/secretsmanager/no_secret \
            test_parameter no_parameter
```
Response
```
{
    "InvalidParameters": [
        "/aws/reference/secretsmanager/no_secret", 
        "no_parameter"
    ], 
    "Parameters": [
        {
            "Type": "SecureString", 
            "Name": "/aws/reference/secretsmanager/test_secret", 
            "Value": "test_secret"
        }, 
        {
            "Version": 1, 
            "Type": "string", 
            "Name": "test_parameter", 
            "Value": "test_parameter"
        }
    ]
}
```
4)Make a ssm get-params request with AWS CLI 2.1.0
Request
```
aws --version
aws-cli/2.1.0 Python/3.7.3 Linux/5.4.39-linuxkit docker/x86_64.amzn.2

aws --endpoint-url http://localstack:4566 ssm get-parameters \
    --names /aws/reference/secretsmanager/test_secret /aws/reference/secretsmanager/no_secret \
            test_parameter no_parameter
```
Response
```
{
    "Parameters": [
        {
            "Name": "/aws/reference/secretsmanager/test_secret",
            "Type": "SecureString",
            "Value": "test_secret",
            "SourceResult": {
                "ARN": "arn:aws:secretsmanager:us-east-1:1234567890:secret:test_secret-oOsrB",
                "Name": "test_secret",
                "VersionId": "73e0517c-bf37-4a0b-925d-41fc260eba28",
                "SecretString": "test_secret",
                "VersionStages": [
                    "AWSCURRENT"
                ],
                "CreatedDate": "2020-11-24T04:29:39.000Z"
            },
            "LastModifiedDate": "2020-11-24T04:29:39+00:00"
        },
        {
            "Name": "test_parameter",
            "Type": "string",
            "Value": "test_parameter",
            "Version": 1,
            "LastModifiedDate": "2020-11-24T02:59:15.368000+00:00",
            "ARN": "arn:aws:ssm:us-east-1:1234567890:parameter/test_parameter"
        }
    ],
    "InvalidParameters": [
        "/aws/reference/secretsmanager/no_secret",
        "no_parameter"
    ]
}
```
We can see that in the old version, the params in the array are simple objects, while in the newer version the secret has a `SourceResult` nested object, which the SDK is not expecting, as it is expecting a `VALUE` and not a `START_OBJECT`.

I'll try to find this precise canonical object, but any help is appreciated 😄

**Comment by jellybeat** [comment]
Hey @whummer! I'm back to this one, sorry about the time taken, EOY has been quite busy.
I'm currently working on the tests in Java utils ([PR draft here](https://github.com/localstack/localstack-java-utils/pull/27)), but I'm having problems building a localstack docker image with the new code in this branch to effectively test those changes. Whenever I run `make docker-build` the build breaks on the `init-testlibs` part with this message:

```
ERROR: 'javac -source 1.8 -target 1.8 -cp "/opt/code/localstack/localstack/utils/kinesis/java:/opt/code/localstack/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/httpclient-4.5.5.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/animal-sniffer-annotations-1.14.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/guava-26.0-jre.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/error_prone_annotations-2.1.3.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/checker-qual-2.5.2.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jmespath-java-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.3.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-codec-1.10.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jsr305-3.0.2.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-lang3-3.7.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/httpcore-4.4.9.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/j2objc-annotations-1.1.jar" /opt/code/localstack/localstack/utils/kinesis/java/cloud/localstack/*.java': exit code 2; output: b'error: No file system provider is available to handle this file: /opt/code/localstack/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.438.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/httpclient-4.5.5.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/animal-sniffer-annotations-1.14.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/guava-26.0-jre.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/error_prone_annotations-2.1.3.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.438.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/checker-qual-2.5.2.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jmespath-java-1.11.438.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.3.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-codec-1.10.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.438.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jsr305-3.0.2.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-lang3-3.7.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.438.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/httpcore-4.4.9.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.438.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.438.jar\nerror: No file system provider is available to handle this file: /opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/j2objc-annotations-1.1.jar\nwarning: [options] bootstrap class path not set in conjunction with -source 8\n'
```

```
Traceback (most recent call last):
  File "localstack/services/install.py", line 304, in <module>
    install_amazon_kinesis_client_libs()
  File "localstack/services/install.py", line 221, in install_amazon_kinesis_client_libs
    run('javac -source %s -target %s -cp "%s" %s' % (
  File "/opt/code/localstack/localstack/utils/common.py", line 1158, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 1155, in do_run
    return bootstrap.run(cmd, **kwargs)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 653, in run
    raise e
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 613, in run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'javac -source 1.8 -target 1.8 -cp "/opt/code/localstack/localstack/utils/kinesis/java:/opt/code/localstack/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/httpclient-4.5.5.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/animal-sniffer-annotations-1.14.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/guava-26.0-jre.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/error_prone_annotations-2.1.3.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/checker-qual-2.5.2.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jmespath-java-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.3.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-codec-1.10.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jsr305-3.0.2.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/commons-lang3-3.7.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/httpcore-4.4.9.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.438.jar:/opt/code/localstack/.venv/lib/python3.8/site-packages/amazon_kclpy/jars/j2objc-annotations-1.1.jar" /opt/code/localstack/localstack/utils/kinesis/java/cloud/localstack/*.java' returned non-zero exit status 2.
make: *** [Makefile:32: init-testlibs] Error 1
```

Clearly it states that it's not able to find the jars specified in the classpath, but shouldn't those already be provided? (from `localstack/java-maven-node-python` maybe?). I'm kind of blocked by this to effectively make the changes. Do you know of another way to build the docker image from this branch?

**Comment by whummer** [comment]
Thanks for the update @jellybeat - merging this PR, so we can continue testing this change in the Java utils repo:  localstack/localstack-java-utils#27 Thanks

**Comment by jellybeat** [comment]
Hey @whummer, thanks for the merge here and in the java utils repo 😄. I hope to shortly have another set of PRs to cover the `getParams` case for getting a param and secret in the same request (for both SDK v1 and v2). But for that I'm kind of blocked by the [above issue](https://github.com/localstack/localstack/pull/3263#issuecomment-757436150). Do you have any kind of hint of what could be the problem? If I could make a local docker image build with the changed code I would be able to test everything and do both PRs at the same time instead of having to wait for one to be merged. Thanks 😃

**Pull request merged**
