### PR TITLE
Taking into account msg attributes for total size

### PR DESCRIPTION
**Pull request by sinecode**
Fix https://github.com/localstack/localstack/issues/7147

### CODE REVIEW

**Comment by sinecode** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by isaac0731** [comment]
L

**Comment by thrau** [comment]
hey @sinecode, thanks for the contribution! looks like your current solution doesn't agree with our SNS tests. looping in @bentsku who is the service owner of SNS.

**Comment by sinecode** [comment]
> hey @sinecode, thanks for the contribution! looks like your current solution doesn't agree with our SNS tests. looping in @bentsku who is the service owner of SNS.

Yeah there was a bug! It should be fixed now but CircleCI seems broken at the moment. Let's see when it will come back...

**Comment by bentsku** [comment]
Hi @sinecode and thanks a lot for your contribution! We had an issue that has recently been fixed in #7176 (see comment: https://github.com/localstack/localstack/pull/7176#pullrequestreview-1180424176) which was blocking our pipeline. Could you please rebase on master to re-trigger the pipeline with the fix? Thank you!

**Comment by sinecode** [comment]
Hi @bentsku. Tests now are green. The PR is ready to be reviewed 😃

**Review by thrau — APPROVED** [review]
This looks pretty good! A go from my side. Happy to let @bentsku give a final signoff and merge.

**Comment by bentsku** [comment]
This looks good to me as well! Thanks again for this fix.

**Comment by thrau** [comment]
thanks very much @sinecode, and welcome to the list of contributors!

**Comment by isaac0731** [comment]
image

**Pull request merged**
