### PR TITLE
fix is_deployed check for sqs resource type

### LINKED ISSUE #2772: Cloudformation fails to update stack with sqs dependency. Unable to resolve all CloudFormation resources after traversing dependency tree
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When running `aws cloudformation update-stack` which adds 2 SQS Queues, where one is a dlq for the other, localstack fails to resolve the dependency between the two and raises the exception: `Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40 reached): `
...

## Expected behavior
...

## Actual behavior
```
2020-07-26T14:43:45:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/ServerlessDeploymentBucket: None
2020-07-26T14:43:45:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'mystack-ServerlessDeploymentBucket-2UMFDVR31WG6'}}
2020-07-26T14:43:45:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "ServerlessDeploymentBucket"
2020-07-26T14:43:45:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'mystack-ServerlessDeploymentBucket-2UMFDVR31WG6', 'ACL': 'public-read'}
2020-07-26T14:43:45:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueue: None
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueueDLQ: None
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::SQS::Queue', 'Properties': {'QueueName': 'hermes-development-events-dlq', 'MessageRetentionPeriod': 1209600}}
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "SQS::Queue" id "EventSQSQueueDLQ"
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "SQS::Queue" in region us-east-1: create_queue {'QueueName': 'hermes-development-events-dlq', 'Attributes': {'MessageRetentionPeriod': '1209600'}, 'tags': {}}
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:INFO:localstack.services.cloudformation.cloudformation_starter: Resource EventSQSQueue cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::SQS::Queue', 'DependsOn': ['EventSQSQueueDLQ'], 'Properties': {'QueueName': 'hermes-development-events.fifo', 'RedrivePolicy': {'deadLetterTargetArn': 'arn:aws:sqs:us-east-1:000000000000:hermes-development-events-dlq', 'maxReceiveCount': 5}}}
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueueDLQ: False
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueue: None
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:INFO:localstack.services.cloudformation.cloudformation_starter: Resource EventSQSQueue cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::SQS::Queue', 'DependsOn': ['EventSQSQueueDLQ'], 'Properties': {'QueueName': 'hermes-development-events.fifo', 'RedrivePolicy': {'deadLetterTargetArn': 'arn:aws:sqs:us-east-1:000000000000:hermes-development-events-dlq', 'maxReceiveCount': 5}}}
2020-07-26T14:44:14:WARNING:localstack.services.cloudformation.cloudformation_starter: Unresolvable dependencies, there may be undeployed stack resources: {'EventSQSQueue': ['EventSQSQueue', {'Type': 'AWS::SQS::Queue', 'DependsOn': ['EventSQSQueueDLQ'], 'Properties': {'QueueName': 'hermes-development-events.fifo', 'RedrivePolicy': {'deadLetterTargetArn': 'arn:aws:sqs:us-east-1:000000000000:hermes-development-events-dlq', 'maxReceiveCount': 5}}}, <moto.cloudformation.parsing.ResourceMap object at 0x7f7875618370>, 'us-east-1']}
2020-07-26T14:44:14:WARNING:bootstrap.py: Thread run method <function apply_patches.<locals>.run_dependencies_deployment_loop.<locals>.run_loop at 0x7f787378a790>(None) failed: Traceback (most recent call last):
  File "/mnt/data/hudo/Projects/localstask-original/localstack/utils/bootstrap.py", line 510, in run
    self.func(self.params)
  File "/mnt/data/hudo/Projects/localstask-original/localstack/services/cloudformation/cloudformation_starter.py", line 847, in run_loop
    raise Exception('Unable to resolve all CloudFormation resources after traversing ' +
Exception: Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40 reached): ['EventSQSQueue']
```

...

# Steps to reproduce
## Command used to start LocalStack
DEBUG=1 make infra

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
cloudformation-template-create-stack.json

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    }
  }
}
```

cloudformation-template-update-stack.json

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "EventSQSQueueDLQ": {
      "Type": "AWS::SQS::Queue",
      "Properties": {
        "QueueName": "hermes-development-events-dlq",
        "MessageRetentionPeriod": 1209600
      }
    },
    "EventSQSQueue": {
      "Type": "AWS::SQS::Queue",
      "DependsOn": ["EventSQSQueueDLQ"],
      "Properties": {
        "QueueName": "hermes-development-events.fifo",
        "RedrivePolicy": {
          "deadLetterTargetArn": {
            "Fn::GetAtt": ["EventSQSQueueDLQ", "Arn"]
          },
          "maxReceiveCount": 5
        }
      }
    }
  }
}
```

`aws cloudformation create-stack --stack-name mystack --template-body file://cloudformation-template-create-stack.json --endpoint-url http://localhost:4566`

`aws cloudformation update-stack --stack-name mystack --template-body file://cloudformation-template-update-stack.json --endpoint-url http://localhost:4566`
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-226) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by hudovisk**
QueueUrls from sqs_client.list_queues() follow the QueueName for its url or if QueueName is not present it follows the strategy of the [Unique Physical Id](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html). From my testing it is something like `stack_name-resource_id-unique_string`.

This fixes #2772 because the method template_deployer.is_deployed was returning false for the resource dependency even it being deployed successfully.

Couldn't find any tests for template_deployer so I am not sure where to put the tests for this case. Let me know if you there is a better place to test this.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-227) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by hudovisk** [comment]
Finally got around the problem. The false result from the check made the `run_dependencies_deployment_loop` background task to change the state of the stack to UPDATE_FAILED right after the update is finished, as you can see from describe-stack-events. This made my serverless deploy command fail. I made a test case that reproduces the error.

```
aws cloudformation describe-stack-events --stack-name mystack --endpoint-url http://localhost:4566 
{
    "StackEvents": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "EventId": "e36aaacc-57c9-4e17-9c9f-74f867d817a9",
            "StackName": "mystack",
            "LogicalResourceId": "mystack",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2020-07-26T19:54:49.764288Z",
            "ResourceStatus": "UPDATE_FAILED"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "EventId": "e5678352-ead1-44d8-9014-781fb98c315d",
            "StackName": "mystack",
            "LogicalResourceId": "mystack",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2020-07-26T19:54:49.698093Z",
            "ResourceStatus": "UPDATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "EventId": "ddc14c0a-a057-4575-b892-64f70e6b88bb",
            "StackName": "mystack",
            "LogicalResourceId": "mystack",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2020-07-26T19:54:49.595477Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS",
            "ResourceStatusReason": "User Initiated"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "EventId": "c50cfd24-126e-4a6a-b72a-92b2c29d4415",
            "StackName": "mystack",
            "LogicalResourceId": "mystack",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2020-07-26T19:54:36.845414Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "EventId": "ecf927d1-ef26-4b8b-9266-c51150cb395d",
            "StackName": "mystack",
            "LogicalResourceId": "mystack",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/mystack/42e39f34-d651-4442-ac9b-b2a16c916663",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2020-07-26T19:54:36.789956Z",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "User Initiated"
        }
    ]
}
```

**Comment by hudovisk** [comment]
Need some help to figure out why the tests are failing

**Comment by hudovisk** [comment]
I think that the tests are failing due to a bug in the moto-ext library. I opened a PR (https://github.com/localstack/moto/pull/8), not sure if it is the right place though, with what I believe is the fix.

**Comment by hudovisk** [comment]
Hey @whummer, did you get a chance of updating moto-ext with upstream?

**Comment by whummer** [comment]
Hey @hudovisk , yes, moto-ext has been updated with upstream in the meantime. Looks like there's still a small assertion error in your tests - I just re-ran the build to make sure this is reproducible. Thanks

**Comment by hudovisk** [comment]
Great, so I spent some more time on it and found that the changes in #2811 had a side effect that I am not sure if it was desired. When updating the QueueName for SQS it creates a difference between the QueueName in the resource_json (which uses the resource name from moto) and the QueueName in the resource_map (which uses the resource name generated in localstack).
```python
# add some fixes and default props which otherwise cause deployments to fail
add_default_props(resource_json, resource_name) # here uses QueueName from moto
for resource in resources_map._resource_json_map.values():
    add_default_props(resource) # Here updates the same Queue but in resource_map with different QueueName
```

When commenting the lines that adds QueueName in `add_default_resource_props` the assertion in the test pass, but the test fails while deleting the stack for some reason that I am not sure yet :sweat_smile:

**Comment by whummer** [comment]
Apologies for the delay @hudovisk . This should be fixed in the meantime - can you please pull the `latest` image and give it another try? Also, I've tried resolving the conflicts on your branch, but looks like some changes would still be required (e.g., variable naming of the CF templates). Would be great if we could update the PR and get it merged, or otherwise close it.. Thanks!

**Comment by thrau** [comment]
Closing this PR due to inactivity and conflicts

**Pull request closed without merging**
