### PR TITLE
KMS sign: Avoid rehashing the already hashed message

### PR DESCRIPTION
**Pull request by paullallier**
This may be an improvement on issue #6815 - hopefully.
May also relate to issue #7158.

### CODE REVIEW

**Comment by paullallier** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by paullallier** [comment]
Not sure why the CI tests fails on something that doesn't seem KMS related...  But is there a CI configuration error more generally?

As far as I can see it's not run the tests in tests/integration/test_kms.py - or several other files in that folder.  Is that intentional?  (I was trying to double-check that my changes had been tested by the existing test.)

**Comment by paullallier** [comment]
I believe my fix is correct though - I've manually applied the change to the localstack docker container I'm running, restarted python, and my JWTs now verify after being signed by localstack KMS in 'RAW' messageType mode - as they do with AWS.

**Comment by laszlovandenhoek** [comment]
I can confirm that running your branch locally (using `python -m localstack.cli.main start --host`) now allows me to create (externally) valid signatures using the `Sign` operation. This is a must-have for verifying JWT tokens. Thanks a lot for finding and fixing this problem just in time for me :) Now let's get this merged ASAP ;)

**Comment by laszlovandenhoek** [comment]
recheck

**Comment by paullallier** [comment]
Hmm.  That test quite failed again, but on a different test.  I guess it's possible that S3 and firehose (which I don't know) both use KMS sign internally for something, and my change has broken it?

**Comment by viren-nadkarni** [comment]
The failures don't seem related to your change.

Thanks for contributing @paullallier !

**Comment by viren-nadkarni** [comment]
@paullallier: We need to add some tests. I'm trying to reproduce the issue so that we can compare the behaviour against AWS. Since you mentioned you're not fluent with Python, I'm happy to take this over.

**Comment by paullallier** [comment]
@viren-nadkarni: Sounds good to me.  There's some information about it here, which might be useful if you haven't seen it already.  https://github.com/localstack/localstack/issues/6815#issuecomment-1458573903

Since we can't extract the private key from AWS, I was struggling a bit to come up with a way to do a like-for-like test.  And I've, personally, only really tested it with EC256 keys so far, since that's what I'm interested in.

**Comment by viren-nadkarni** [comment]
Closing in favour of https://github.com/localstack/localstack/pull/7878

Thanks again @paullallier for the findings!

**Pull request closed without merging**
