### PR TITLE
Firehose kinesis source

### PR DESCRIPTION
**Pull request by derrick-mink-sp**
**Please refer to the contribution guidelines in the README when submitting PRs.**

### CODE REVIEW

**Comment by whummer** [comment]
This looks great, thanks @derrick-mink-sp ! Do you think we could add a small test to cover this new feature?

**Comment by derrick-mink-sp** [comment]
Fix a couple issues with ARN for Kinesis Streams and added an integration test

**Comment by whummer** [comment]
@derrick-mink-sp Great, thanks! Just one more nitpick comment, to avoid a (too) long `sleep` time

**Comment by derrick-mink-sp** [comment]
Reduced sleep to 3s to align with other integration tests

**Pull request merged**
