### PR TITLE
Transcribe: Support output bucket name and output key

### PR DESCRIPTION
**Pull request by kkocel**
Fixes https://github.com/localstack/localstack/issues/8089

### CODE REVIEW

**Comment by kkocel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kkocel** [comment]
Not yet but I have x86 Mac so I will try to add tests. I saw another PR but it does not resolve my issue? Have you seen it?

**Comment by viren-nadkarni** [comment]
> Not yet but I have x86 Mac so I will try to add tests. I saw another PR but it does not resolve my issue? Have you seen it?

Could you point them out to me? Thanks

**Comment by kkocel** [comment]
@viren-nadkarni see https://github.com/localstack/localstack/issues/8089#issuecomment-1567888123

**Comment by sannya-singal** [comment]
> @viren-nadkarni see [#8089 (comment)](https://github.com/localstack/localstack/issues/8089#issuecomment-1567888123)

Thanks @kkocel for the PR 🙂🚀. Since the changes are already pushed in #8265, I am closing this PR and will followup [here](https://github.com/localstack/localstack/issues/8089#issuecomment-1568457625).

**Comment by sannya-singal** [comment]
Thanks @kkocel for the PR 🙂🚀. Since the changes are already pushed in https://github.com/localstack/localstack/pull/8265, I am closing this PR and will followup https://github.com/localstack/localstack/issues/8089#issuecomment-1568457625.

**Pull request closed without merging**
