### PR TITLE
Upgrade ElasticSearch 6.5

### PR DESCRIPTION
**Pull request by dmnlk**
https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-elasticsearch-service-announces-support-for-elasticsearch-6-5/?nc1=h_ls

### CODE REVIEW

**Comment by dmnlk** [comment]
build failed ...
oracle-java8-installer

**Comment by dmnlk** [comment]
@whummer I think we should migrate to jdk11 or later

**Comment by whummer** [comment]
Looks like a new version 7.0.1 got released @dmnlk : https://pypi.org/project/elasticsearch/ Can we update this PR? Thanks

**Comment by dmnlk** [comment]
@whummer ok ,I'll update this PR

**Comment by dmnlk** [comment]
@whummer AWS ElasticSearch Sevice doesn't  support ES7.0 yet, therefore localstack shoudn't require elasticsearch 7.0.1 module from pip

>For Elasticsearch 7.0 and later, use the major version 7 (7.x.y) of the library.

**Comment by whummer** [comment]
OK, thanks for clarifying @dmnlk . The problem, though, is that version 6.5.0 was apparently never released on pypi. Therefore the tests are failing on this branch. Any ideas?

**Comment by dmnlk** [comment]
hmm
I tried build localstack docker image on my local machine.
but, make init process is succeeded.

```
WARNING: You are using pip version 19.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 5336b84a6052
 ---> 11a11b53e7fa
Step 13/27 : ADD localstack/package.json localstack/package.json
 ---> 1c07fad64a93
Step 14/27 : ADD localstack/services/__init__.py localstack/services/install.py localstack/services/
 ---> 49e8ddde4ff7
Step 15/27 : RUN make init
 ---> Running in 521d44b34d2a
. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py libs
INFO:__main__:Downloading and installing local ElasticMQ server. This may take some time.
INFO:__main__:Downloading and installing local Step Functions server. This may take some time.
INFO:__main__:Downloading and installing LocalStack Java libraries. This may take some time.
Initializing installation.
Done.
Removing intermediate container 521d44b34d2a
 ---> 11d59cab23d8
Step 16/27 : ADD localstack/dashboard/web localstack/dashboard/web
 ---> cdfa95acac16
```
I'm searching behavior  difference  my env and travis now

**Comment by dmnlk** [comment]
ok i figured out this problem.
`ingest-attachment  ` plugin required additional permisson therefore stop by prompt

```
[git][* es-version-6.5]:/Volumes/src/github.com/dmnlk/localstack/ /Volumes/src/github.com/dmnlk/localstack/localstack/infra/elasticsearch/bin/elasticsearch-plugin install ingest-attachment                  
-> Downloading ingest-attachment from elastic
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.sun.java2d.cmm.kcms
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
```
so, i add `-b ` option which is for CI and  add verbose log
https://www.elastic.co/guide/en/elasticsearch/plugins/current/_other_command_line_parameters.html#_batch_mode

```
. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py libs
Initializing installation.
INFO:__main__:Downloading and installing local DynamoDB server. This may take some time.
INFO:__main__:Downloading and installing local Kinesis server. This may take some time.
INFO:__main__:Downloading and installing local ElasticMQ server. This may take some time.
INFO:__main__:Downloading and installing local Elasticsearch server. This may take some time.
INFO:__main__:Downloading and installing local Step Functions server. This may take some time.
install elasticsearch-plugin analysis-icu
install elasticsearch-plugin ingest-attachment
install elasticsearch-plugin ingest-user-agent
install elasticsearch-plugin analysis-kuromoji
install elasticsearch-plugin mapper-murmur3
install elasticsearch-plugin mapper-size
install elasticsearch-plugin analysis-phonetic
install elasticsearch-plugin analysis-smartcn
install elasticsearch-plugin analysis-stempel
install elasticsearch-plugin analysis-ukrainian
INFO:__main__:Downloading and installing LocalStack Java libraries. This may take some time.
Done.
```

**Comment by dmnlk** [comment]
@whummer passed test 💪

**Comment by dmnlk** [comment]
should be squash commit, after review

**Comment by whummer** [comment]
Thanks for fixing this @dmnlk !

**Pull request merged**
