### PR TITLE
pin docker dependency to <7.0.0

### PR DESCRIPTION
**Pull request by dominikschubert**
## Motivation
It doesn't seem to break anything here yet but it technically could lead to the same kind of issues for users of community.

Recently the docker PyPI package was updated to 7.0.0 which started breaking integration tests in -ext with the following kind of exception:
```
docker.errors.DockerException: invalid tag 'localhost.localstack.cloud:4514/r-a9dfa6f4:latest': invalid reference format` anymore.
```

## Context

Change that was included in their `7.0.0` release: https://github.com/docker/docker-py/pull/3191

## Changes

- pin `docker` dependency to `<7.0.0` to avoid the breaking change for now until we know how to circumvent this

### CODE REVIEW

**Review by dfangl — APPROVED** [review]
Thanks for the quick fix!

**Comment by dfangl** [comment]
Already reported upstream: https://github.com/docker/docker-py/issues/3195
Should be fixed by: https://github.com/docker/docker-py/pull/3196

**Comment by dominikschubert** [comment]
Failure of `test_kinesis_firehose_opensearch_s3_backup` seems like a flake

**Comment by consideRatio** [comment]
Reported this as a bug in https://github.com/docker/docker-py/issues/3240

**Comment by alexrashed** [comment]
Hi @consideRatio!
It seems like there might be a misunderstanding. The bug was already reported and fixed in docker-py (see the comment from @dfangl above). There just isn't a release containing the fix yet.
However, we are pinning the version of `docker-py` until the release is out so you shouldn't see this issue in LocalStack.

**Comment by consideRatio** [comment]
Oh, thank you for helping me get that!

**Pull request merged**
