### PR TITLE
Adding support to docker_lambda variable DOCKER_LAMBDA_API_PORT

### PR DESCRIPTION
**Pull request by wapmesquita**
After the PR https://github.com/lambci/docker-lambda/pull/218 we got the issue #1777. This PR is to try to solve this.

* Defining a new value to DOCKER_LAMBDA_API_PORT and DOCKER_LAMBDA_RUNTIME_PORT port on each lambda container execution when network mode `host`.

### CODE REVIEW

**Comment by wapmesquita** [comment]
It still does not work because of this line: https://github.com/lambci/docker-lambda/blob/2f584c4b0615c1e0a28b007380c800cb7d1a7e58/provided/run/init.go#L149

**Comment by wapmesquita** [comment]
The PR https://github.com/lambci/docker-lambda/pull/235 is part of the changes.

**Comment by whummer** [comment]
Awesome, thanks so much for this fix @wapmesquita ! The PR is still in "draft" mode - is it ready to review and merge? Thanks

**Comment by wapmesquita** [comment]
> Awesome, thanks so much for this fix @wapmesquita ! The PR is still in "draft" mode - is it ready to review and merge? Thanks

Now that there are new docker_lambda images released, it's ready for review and merge.

**Comment by whummer** [comment]
Great, thanks again!

**Pull request merged**
