### PR TITLE
firehose-preserver-batch-order ensure order or uuids in batch

### PR DESCRIPTION
**Pull request by yaitskov**
**Please refer to the contribution guidelines in the README when submitting PRs.**

### CODE REVIEW

**Comment by yaitskov** [comment]
Original service preserves insert order on listing entries. 
FireHose emulator generates random suffixes for batch entries which shufles order randomly them for listing. The simplest hack is to pregenerate uuids for for whole batch,  sort them and zip with entries before persisting them.

**Comment by yaitskov** [comment]
Consequent launches of failing test:
```
        expected: ["one","two","three"]
         but got: ["one","three","two"]
```

```
        expected: ["one","two","three"]
         but got: ["three","two","one"]
```

**Comment by yaitskov** [comment]
@whummer, I need support with this issue too.

**Comment by whummer** [comment]
Thanks a lot for tackling this issue @yaitskov ! So, my understanding is that the root cause of the issue you're facing is that LocalStack is storing one individual S3 object for each record in a batch, whereas real AWS creates a single S3 file to persist all records in a batch. Is that accurate?

If the above statement is true, then I'm wondering if we should rather fix the root cause (i.e., store one S3 file with all records in the batch), rather than creating a workaround based on IDs that are stored in alphanumerical order. What do you think - would that solve the issue as well?

(Please note - I see that this PR solves the actual issue you're facing, but in general we're aiming to replicate the real behavior in AWS as closely as possible, and avoid workarounds whereever possible.)

**Comment by yaitskov** [comment]
Emulator is emulator. It exists to fool tests. 
This PR turns 1 test green. 
If 0 zero tests go red then why not merge.
Random uuids are still random.
Random includes order
FireHose buffers individual messages and puts into same file, right?
Client sends small individual messages one after another.
Order is preserved among them in this case.

**Comment by whummer** [comment]
Thanks for the feedback, appreciate the open discussion.

> This PR turns 1 test green.
> If 0 zero tests go red then why not merge.

I'm afraid cannot fully agree with this statement. The thing is that - given the number of teams using this platform, *every* change we make potentially has some subtle side-effects. Therefore, I can already *anticipate* that some tests (somewhere, by some team) will go to red. Hence, the goal is not to merge changes that, coincidentally, happen to fix some isolated tests by certain users, but to replicate the behavior of AWS as closely as possible (as this is our ultimate "source of truth").

Having said that - can you confirm that, in your particular use case, your tests would be fixed if the LocalStack behavior was identical to that of AWS (i.e., storing batches of records into a single file)? The change would actually be relatively easy to make! (But first, let me quickly verify whether that's the actual behavior on AWS.) Thanks for your support.

**Comment by yaitskov** [comment]
I didn't get your point. 
If you cannot merge it then consider following PR, it will allow to patch service on start.
https://github.com/localstack/localstack/pull/2872

**Comment by whummer** [comment]
Hi @yaitskov , sorry, didn't make myself clear. Let me try to explain one more time.

1 We are facing the situation of a failing test, caused by out of order processing of batch resources
1. The root cause of this issue is a discrepancy between the behavior in LocalStack and real AWS (batch records being stored in single files vs. individual files) 
1. This PR proposes a solution which fixes the issue for the particular failing test, but does **not** address the discrepancy between LocalStack and AWS
1. My point is that we should address the root cause of the discrepancy (i.e., try to make LocalStack behave as closely to AWS as possible), instead of adding this workaround

I have a different proposal: Can you please create a small PR where you add a **failing test** to our Python integration tests, and we can then work together on a proper fix for this issue? Thanks for your help!

**Comment by whummer** [comment]
Superseded by #2911

**Pull request closed without merging**
