### PR TITLE
Update coveralls config

### LINKED ISSUE #4200: Fix coveralls coverage reporting
It seems the nosetest run isn't collecting the coverage data correctly, as the .coverage database is empty after a docker build. Therefore the coveralls script isn't reporting anything.

### PR DESCRIPTION
**Pull request by thrau**
fixes #4200

### CODE REVIEW

**Comment by thrau** [comment]
slow build times in docker could have the same reason as this issue: https://github.com/pytest-dev/pytest-cov/issues/159

**Comment by thrau** [comment]
still one issue left to get it over the line:
the coverage database includes the absolute file paths to code files. the path inside the docker containers are `/opt/code/localstack/...`, once copied outside of the container, the files are under a different path and therefore the coverage data isn't reported correctly.

**Comment by thrau** [comment]
Coverage results are not correct in coveralls now... Maybe relative paths will work: https://github.com/nedbat/coveragepy/issues/597

**Comment by thrau** [comment]
:tada: coverage results are back online! https://coveralls.io/jobs/82683779

**Comment by whummer** [comment]
Awesome 🎉 , thanks @thrau !!

**Pull request merged**
