### PR TITLE
Secret Manager Support for AWS services

### PR DESCRIPTION
**Pull request by jhalaria**
* Add Secrets Manager support
* Integration test to create and retrieve secret
* PR open to add this to the python-client https://github.com/localstack/localstack-python-client/pull/11

### CODE REVIEW

**Comment by jhalaria** [comment]
The build fails because PORT_SECRETSMANAGER isn't available. That comes from an upstream localstack-python client package. I have a PR open with them. Once that gets merged, I will update the client version and then this should be fixed.

**Comment by jhalaria** [comment]
@whummer - Please review.

**Comment by whummer** [comment]
Looks great, thanks @jhalaria !

The python client library has been updated - Can we please update the version to `0.6` here:
https://github.com/localstack/localstack/blob/master/requirements.txt#L19

Can we also bump the version of the Java library to `0.1.15` here: https://github.com/localstack/localstack/blob/master/localstack/ext/java/pom.xml#L8
https://github.com/localstack/localstack/blob/master/localstack/constants.py#L33
https://github.com/localstack/localstack/blame/master/README.md#L296

Thanks

**Comment by jhalaria** [comment]
@whummer - Thank you for looking at the PR. I have addressed your feedback. However the build is failing in a Kinesis test which seems unrelated. Not sure if this is an intermittent error. Thoughts?

**Comment by whummer** [comment]
Tests are fixed now - thanks again!

**Comment by frank-bee** [comment]
I get this error here:
```
com.amazonaws.SdkClientException: Unable to unmarshall response (Invalid format: "2018-05-23 13:16:57.198000" is malformed at " 13:16:57.198000"). Response Code: 200, Response Text: OK

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1599)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1292)
```

when running this code:
```
com.amazonaws.SdkClientException: Unable to unmarshall response (Invalid format: "2018-05-23 13:16:57.198000" is malformed at " 13:16:57.198000"). Response Code: 200, Response Text: OK

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1599)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1292)
```

**Pull request merged**
