### PR TITLE
AWS S3 sets the content-type to `binary/octet-stream` for GET Requests

### PR DESCRIPTION
**Pull request by TheJefe**
This allows a browser to download it as a file, rather then try to
render it in the browser.

fixes https://github.com/localstack/localstack/issues/564 
^^ issue contains reproduction steps and more detail

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @TheJefe ! The build in Travis-CI is failing due to a minor issue with local SSL certificate validation, we'll fix that in a follow-up PR. thanks again

**Comment by viniciuskneves** [comment]
@TheJefe I've done the same test here, using a .html file stored in S3 and the content-type returned is ``text/html`` and not ``binary/octet-stream``. 
I've came to that after updating to the last version of localstack and some of my tests started crashing out of the blue.

> HTTP/1.1 200 OK
  Accept-Ranges: bytes
  Content-Type: text/html
  Content-Length: 487
...

Are you sure that it should always return ``binary/octet-stream``?

**Comment by TheJefe** [comment]
hmm, i'm not sure, I'll need to test it to see.

**Comment by TheJefe** [comment]
oh dear, yep, @viniciuskneves , looks like that is correct. This means the original issue is likely with the default content-type in uploads. Then that same content-type will be used when responding to a GET request.

I used this to confirm the behavior with actual AWS S3

```python
import boto3
import os
from botocore.config import Config
import requests

bucket_name = 'test'
filepath = 'blah.txt'
key = 'blah.txt'

s3 = boto3.resource(
    's3',
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
    aws_session_token=os.getenv('AWS_SESSION_TOKEN'),
)

bucket = s3.Bucket(bucket_name)

bucket.upload_file(filepath, key, ExtraArgs={"ACL": 'public-read', "ContentType": 'text/html'})
url = s3.meta.client.generate_presigned_url('get_object', ExpiresIn=0, Params={'Bucket': bucket_name, 'Key': key})
url = url.split('?')[0]
response = requests.get(url)
print 'Response content-type for text/html: ' + response.headers['Content-Type']

bucket.delete_objects(Delete={'Objects': [{'Key': key},],})

bucket.upload_file(filepath, key, ExtraArgs={"ACL": 'public-read', "ContentType": 'binary/octet-stream'})
url = s3.meta.client.generate_presigned_url('get_object', ExpiresIn=0, Params={'Bucket': bucket_name, 'Key': key})
url = url.split('?')[0]
response = requests.get(url)
print 'Response content-type for binary/octet-stream: ' + response.headers['Content-Type']
```

I'll revert this PR

**Comment by TheJefe** [comment]
annnnd not so easy, it has already been moved around a bit.

The Content-Type used in the GET response should be the same Content-Type that was used in uploading, and if none is provided in the upload, the default of binary/octet-stream should be used.

**Comment by viniciuskneves** [comment]
Yes, exactly! Will you work on it? I've opened an issue regarding this: https://github.com/localstack/localstack/issues/581

If you need some help, let me know!

**Pull request merged**
