### PR TITLE
Implement LambdaContext.get_remaining_time_in_millis.

### PR DESCRIPTION
**Pull request by ACarsonBull**
Added the functionality to keep track fo how long a lambda has been running. get_remaining_time_in_millis() now will return how much longer the lambda can run before it will be killed.

Tests: To test this we implemented test_lambda_remaining_time() that runs two lambdas. The first lambda sleeps for 5 seconds and then we check to make sure it has passed it's timeout. The other returns instantly and a check is done to make sure that there is still time left in its 5 second timeout.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-84) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @ACarsonBull . Looks like there are some lint errors (see Travis-CI build logs) - can we please fix them. Thanks

**Comment by whummer** [comment]
Trying one more time - @ACarsonBull can we please fix the conflicts on this branch and resolve the lint errors? Thanks!

**Comment by winly19** [comment]
changes-requested

**Comment by rmsmani** [comment]
@whummer Can i Take up this?

**Comment by thrau** [comment]
Closing this PR due to inactivity and conflicts

**Pull request closed without merging**
