### PR TITLE
change batch size range values for sqs

### PR DESCRIPTION
**Pull request by lionas32**
Not sure if these are the only files that need changing. Should I also add more tests?

Based on the `BatchSize` values documented in https://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html#SSS-CreateEventSourceMapping-request-BatchSize.

Appreciate any feedback 🙂

### CODE REVIEW

**Comment by lionas32** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by lionas32** [comment]
recheck

**Review by thrau — COMMENTED** [review]
Hi @lionas32, thanks for the contribution, and sorry for the late reply!

I think the biggest issue with this is that we currently cannot support batch sizes >= 10, as explained [here](https://github.com/localstack/localstack/issues/5042#issuecomment-1207394650).
It would require a significant rework of the event source listener.

If we support bigger batch sizes, i think we should also test that they work.

**Comment by lionas32** [comment]
Gotcha, thanks for the clarification! I'll just close it

**Pull request closed without merging**
