### PR TITLE
Add swf support from moto

### PR DESCRIPTION
**Pull request by redparham**
Integrate moto swf support:
https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md#swf

Possibly satisfy this issue:
https://github.com/localstack/localstack/issues/116

### CODE REVIEW

**Comment by redparham** [comment]
Looks like build failed waiting for kms port... seems unrelated. Maybe someone can comment?

>   File "/home/travis/build/localstack/localstack/localstack/services/kms/kms_starter.py", line 25, in start_kms
    wait_for_port_open(backend_port)
  File "/home/travis/build/localstack/localstack/localstack/utils/common.py", line 496, in wait_for_port_open

**Comment by redparham** [comment]
There are a few small changes to make to moto/swf modules. From the [developer guide](https://github.com/localstack/localstack/tree/master/doc/developer_guides#patchingreleasing-a-third-party-libraries), it appears those can made to the moto-ext fork:
https://github.com/whummer/moto/tree/localstack-fixes. But that fork appears to be outdated - I don't see the code I need to change there because its too old. Is that fork still being used?

**Comment by whummer** [comment]
Looks great, thanks for adding this @redparham ! 👍 

> There are a few small changes to make to moto/swf modules. From the developer guide, it appears those can made to the moto-ext fork.

Please feel free to contribute these changes to upstream `moto` directly. We regularly pull the latest version of upstream `moto` into `moto-ext` and release new snapshots, which then become available in LocalStack itself. Hope that helps - thanks for your support.

**Comment by redparham** [comment]
Great, thanks. BTW, those moto changes are here:
https://github.com/spulec/moto/pull/3680

**Comment by redparham** [comment]
Looks like moto changes I mentioned have been accepted:
https://github.com/spulec/moto/pull/3680

**Comment by tony-dot-sh** [comment]
> Looks like build failed waiting for kms port... seems unrelated. Maybe someone can comment?
> 
> > File "/home/travis/build/localstack/localstack/localstack/services/kms/kms_starter.py", line 25, in start_kms
> > wait_for_port_open(backend_port)
> > File "/home/travis/build/localstack/localstack/localstack/utils/common.py", line 496, in wait_for_port_open

@redparham Did you ever get this figured out? Testing with `make infra` and it bails on me at the same spot (wondering if it's an ENV VAR or something)

**Comment by whummer** [comment]
@tony-dot-sh In case you run LocalStack in local dev mode via `make infra` (which should only be used for development), then sometimes it can happen that the local KMS tmp folder becomes corrupted - can you try deleting `/tmp/local-kms` and start up again?

@redparham - we'll pull latest `moto` and release a new version shortly.. 👍  Thanks

**Comment by tony-dot-sh** [comment]
@whummer ended up being the `localstack/infra/kms` dir and contents that gets created during `make infra`. Something in there made it unhappy. Once I nuked that whole `infra`  dir and tried `make infra` again, it worked fine. Thanks!!

**Pull request merged**
