### PR TITLE
Add basic EventBridge (CloudWatch Events) support

### PR DESCRIPTION
**Pull request by eoinsha**
This adds a moto server for CloudWatch Events / EventBridge.

Relates to issue #103 but does not add a full implementation with event triggering. The benefit of merging this PR is that you can invoke CloudWatch Events APIs like `put_rule` and `put_events` against a local target. A separate PR would be required to add full event bus support with scheduled events, triggers and targets.

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @eoinsha . Do you think we could add a very basic integration test with a few simple API calls like `put_rule` and `put_events`? Thanks!

**Comment by eoinsha** [comment]
Sure, @whummer. Tests added via 97b00e1c6428b98c752edbb86d684783ab4692

**Comment by whummer** [comment]
Awesome - thanks again 👍

**Comment by eoinsha** [comment]
Great - thanks @whummer Is it possible to get a release (DockerHub) of this feature or understand when this might happen?

**Comment by romipetrelis-evive** [comment]
Is event triggering supported using a Lambda function? We've done `events put-rule`, `lambda add-permission`, and `events put-targets` but are not seeing the events trigger the lambdas.

**Pull request merged**
