### PR TITLE
Allow direct upload of Java JAR in Lambda API

### PR DESCRIPTION
**Pull request by jharriman**
Localstack currently expects Java Lambda functions to be uploaded as a `.jar` wrapped in a `.zip` file. As #385 notes, this is not what the Lambda API expects to be in the `ZipFile` payload. Instead it expects: 
```
1. "Fat" JAR - single jar file with all dependencies
2. ZIP - zip archive with class files in / and jar files in /lib
```
This PR allows localstack to accept format 1. 

Format 2 is a little harder to implement because it would require re-working the Java executor to handle the different locations of the class files in `/` and jar files in `/`. 

This change also cleans up some of the handler paths in the `set_function_code` function. The goal is be more explicit about how to properly form handlers for non python (and in particular Java) runtimes. I've tried to add addition documentation via docstrings and comments (aside: @whummer, I'm not seeing any consistent docstring format. I've used the `reStructuredText` format here, though I'm more familiar with the docstring format here: http://google.github.io/styleguide/pyguide.html?showone=Comments#Comments).

### CODE REVIEW

**Comment by jharriman** [comment]
Looks like this error is being caused by: https://github.com/localstack/localstack/issues/721

**Comment by whummer** [comment]
@jharriman #721 has been fixed in the meantime - I tried rerunning the build but there still seems to be an issue. Can you take a look? Thanks

**Comment by whummer** [comment]
Seems like the tests are passing - merging now, thanks again!

**Comment by bcosynot** [comment]
@jharriman I am trying to upload a JAR and I am getting `An error occurred (ValidationError) when calling the CreateFunction operation: ZIP file for the java8 runtime not yet supported.`

Do you know why that might be happening?

**Pull request merged**
