### PR TITLE
Bind endpoints to access SMS messages sent via SNS

### PR DESCRIPTION
**Pull request by rutviklhase**
**Please refer to the contribution guidelines in the README when submitting PRs.**
Extension of the original PR #7936, includes the commit from the original author.

### CODE REVIEW

**Comment by rutviklhase** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rutviklhase** [comment]
recheck

**Comment by bentsku** [comment]
Hi @rutviklhase, would it be possible to rebase your PR on the latest `master` branch? The latest commit from LocalStack in your branch dates from March 22nd, which is triggered all the CI failures. Thanks!

**Comment by rutviklhase** [comment]
Hi @bentsku ! 
Sure I can rebase on the latest master branch.

**Pull request closed without merging**
