### PR TITLE
Fix cloudformation get template

### PR DESCRIPTION
**Pull request by deepak2431**
Fix for issue #7657 

Now the get-template response for the command with created stack-name "test-stack": 
`awslocal cloudformation get-template --stack-name test-stack` returns

``` {
    "TemplateBody": {
        "Resources": {
            "topic69831491": {
                "Type": "AWS::SNS::Topic"
            }
        },
        "Outputs": {
            "TopicName": {
                "Value": {
                    "Fn::GetAtt": [
                        "topic69831491",
                        "TopicName"
                    ]
                }
            }
        },
        "StackName": "test-stack",
        "ChangeSetName": "awscli-cloudformation-package-deploy-1678120472"
    },
    "StagesAvailable": [
        "Original",
        "Processed"
    ]
}
```

### CODE REVIEW

**Comment by deepak2431** [comment]
@pinzon You can review it.

**Comment by deepak2431** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by deepak2431** [comment]
recheck

**Comment by pinzon** [comment]
The issue is already solved in newer versions of LocalStack. Thanks for confirming it @deepak2431.

**Pull request closed without merging**
