### PR TITLE
Refactor Events test

### PR DESCRIPTION
**Pull request by pinzon**
This small PR addresses the last comment made on #5878. 

Changes:
- Test refactor for more clarity and more validations

### CODE REVIEW

**Comment by pinzon** [comment]
I made the test easier to read using pytest.parametization while reviewing the feature for the last comment in #5878.

**Comment by dfangl** [comment]
@pinzon It seems the test now fails in CI with the "AUTH2" parameter, can you look into it?
As a side note: we generally prefer fstrings wherever we refactor stuff, there are quite some uses of both format and % based string formatting in your changes, would be nice if you could change those to fstrings when you are fixing the test! Thanks!

**Comment by pinzon** [comment]
@dfangl thanks for the review!. I fixed the tests and made the corrections.

**Review by dfangl — APPROVED** [review]
LGTM! Thanks for making the fixes!

**Pull request merged**
