### PR TITLE
Fix bug #4295

### PR DESCRIPTION
**Pull request by jrauen**
Proposed fix for bug #4295.

**Please refer to the contribution guidelines in the README when submitting PRs.**

### CODE REVIEW

**Review by josephpohlmann — COMMENTED** [review]
Upvote.  This is far more consistent of a date format.

**Comment by jrauen** [comment]
After a bit more research this looks to be an issue with the Terraform AWS provider. The [AWS CLI documentation](https://docs.aws.amazon.com/cli/latest/reference/lambda/publish-version.html) shows the expected timestamp format as `2019-09-23T18:32:33.857+0000` which is what localstack is currently returning. The issue with #4295 is that the Terraform provider is expecting a format using Go's `time.RFC3339`.

**Comment by whummer** [comment]
Thanks for digging into this @jrauen ! 

> After a bit more research this looks to be an issue with the Terraform AWS provider. The AWS CLI documentation shows the expected timestamp format as 2019-09-23T18:32:33.857+0000 which is what localstack is currently returning

In this case I'd rather trust the Terraform AWS provider as the "source of truth" - it is usually much more up-to-date than the AWS docs themselves. If this has been tested and works again TF - should we re-open and merge this PR? Thanks!

**Comment by jrauen** [comment]
So i re-closed this PR because I'm not convinced I was right again. It's been a whirlwind of bouncing around AWS tools from the TF provider, AWS GO SDK, and checking the service API timestamps themselves. I'm still not quite sure _where_ the problem lies exactly, but the timestamps coming from the wire align with what localstack is providing so it's definitely not localstack. At least, it's not localstack acting different than the service API (which may itself be sending incorrect timestamps). I'll continue to research.

**Comment by jrauen** [comment]
I think I came up with the solution but I've put it in PR #4323 so we can keep the git history clean with a single commit.

**Pull request closed without merging**
