### PR TITLE
Added support for running SSM via moto

### PR DESCRIPTION
**Pull request by terrycain**
Have added lines for running SSM via moto. Opinions on this?

Also haven't included tests as its running via moto so really moto should test SSM right? But I can add some if needed.

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @terrycain , we don't need exhaustive functional tests, but a simple test that makes sure the service is running properly would be nice (e.g., a simple `list_documents()` call or something like that).
Can we please also add a line with the default service endpoint to the `README`. Thanks

**Comment by terrycain** [comment]
Ahh sure :-), will get that done at some point today. Do you mind if I create other PRs for any service moto supports but localstack does not?

**Comment by whummer** [comment]
Awesome, thanks @terrycain . Sure, happy to accept follow up PRs for other services.

However, as the number of services increases, we'll have to think about whether all services should be spun up by default. For example, only a few users will need to use SSM. I feel like we should add support for user profiles with customizable sets of services - then we can define a "core" profile (with the most popular core services) and an "extended" profile (with extended services like SSM), something like that.

**Comment by terrycain** [comment]
Yeah sounds good. Yeah I use SSM heavily for the "encrypted" parameter store for my ecs containers. Profiles should be good.

**Pull request merged**
