### PR TITLE
Use latest docker image with docker compose

### PR DESCRIPTION
**Pull request by Sagar2366**
Use latest docker image with docker compose

### CODE REVIEW

**Comment by Sagar2366** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by Sagar2366** [comment]
recheck

**Comment by HarshCasper** [comment]
Hi @Sagar2366 — Anything we can possibly help with this PR 😄 ?

**Comment by Sagar2366** [comment]
No @HarshCasper  , PR is closed.

**Pull request closed without merging**
