### PR TITLE
Add Nix and Flox to installation methods

### PR DESCRIPTION
**Pull request by bryanhonof**
## Motivation

LocalStack is available in Nix and Flox, and it seems to be working well with those 2 packages managers.

## Changes

Just README changes, no functionality has changed.

### Nix

1. Install the [Nix package manager](https://nixos.org/download/) and follow the steps in the README.
2a. For Nix installations that have the `nix-command` and `flakes` experimental features enabled, one can use `nix profile install`.
2b. In the case those experimental features aren't enabled, use either `nix-shell` or `nix-env`.

### Flox

1. Install the [Flox CLI](https://flox.dev/docs/install-flox/).
2. Create a Flox environment in the current working directory with `flox init`
3. Install `localstack` with `flox install localstack`
4. Activate the environment with `flox activate`

After that, localstack will be available to the user as long as the environment is activated.

### CODE REVIEW

**Comment by bryanhonof** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by alexrashed — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution, @bryanhonof!
However, the nix package for LocalStack is not maintained by us but by the nix community and it is quite outdated (we are about to release 3.5 tomorrow, [the nix package points towards 3.0.0](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/localstack/default.nix)).
While we really appreciate the community maintaining all these different packaging formats, I don't think we should really actively advertise them for as long as we cannot guarantee that they will be kept up to date.

**Comment by bryanhonof** [comment]
@alexrashed That's completely understandable.
I'll go a head and close this PR for now, then.
Maybe we can revisit it at a later date. 😁

**Comment by alexrashed** [comment]
Thanks for your understanding!

**Pull request closed without merging**
