### PR TITLE
Addition of Moto S3Control Service

### PR DESCRIPTION
**Pull request by pinzon**
This PR addresses #5168, where the user tries to create a resource using Terraform but the service it needs isn't available. Thankfully Moto already provides partially the service, at least enough so the user can create the resource he wants.

Changes:
- Edge now detects if an S3 request is in reality for the S3control service.
- Starting of the S3control service.
- Addition of tests for the PublicAccessBlock lifecycle and some validations.

For this PR to work correctly it should be merged after spulec/moto#4885 has been integrated.

### CODE REVIEW

**Comment by pinzon** [comment]
Hi @whummer , this last commit changes the way the s3control service is integrated, as you suggested on the Slack.
For the tests to pass they need moto-ext to be updated, I'll be waiting to rebase my branch.

**Comment by whummer** [comment]
Thanks @pinzon , moto-ext has been updated in the meantime - re-running the CI build now, to see if that fixes the tests..

**Review by whummer — APPROVED** [review]
LGTM, nice set of changes @pinzon ! 👍 Should be good to merge, once the tests are fully passing.

**Comment by pinzon** [comment]
Mmm for some reason the s3control provider is not being found, I'll check if I miss something.

**Comment by pinzon** [comment]
@whummer I'm not sure why the test is failing in CircleCI, locally it works fine. 
imagen

and I make sure to run `make clean install entrypoints` before running the tests.

**Comment by pinzon** [comment]
@whummer I changed this service tests to use the `localhost.localstack.cloud` domain for the endpoint_url. hopefully this will fix the errors in CircleCi.

**Comment by whummer** [comment]
LGTM, thanks for updating/fixing the tests @pinzon 👍

**Pull request merged**
