### PR TITLE
Rely on S3 create bucket idempotency in us-east-1

### PR DESCRIPTION
**Pull request by viren-nadkarni**
## Motivation

S3 `CreateBucket` is supposed to be idempotent in `us-east-1`. However, due to [failing tests](https://github.com/localstack/localstack/pull/8912/commits/6b23f6c114af828496d10507780d9154c9a75203) in a merge commit, a use case of this behaviour was removed in https://github.com/localstack/localstack/pull/8912/commits/cb6c4f196018ef4ab6dbf265ce9f4943d0e5d350.

cc: @dfangl 

## Implementation

This PR attempts to understand why this idempotent behaviour disappeared all of a sudden.

### CODE REVIEW

**Comment by dfangl** [comment]
Thanks for this PR. Let's see if we can trigger the behavior we have discovered in other PRs, and find the root cause!

**Comment by viren-nadkarni** [comment]
Looks like the issue no longer persists. A cosmic ray bit flip?

**Review by dfangl — APPROVED** [review]
I think this is good to merge currently, but I feel this issue will arise again at some point :(

**Comment by joe4dev** [comment]
> this issue will arise again at some point :(

... sooner than later 😢 . Failing CI run: https://app.circleci.com/pipelines/github/localstack/localstack/17611/workflows/92c47386-b455-40f5-bf08-d7dd2aff4cf0/jobs/134293

Raw CircleCI logs: https://circleci.com/api/v1.1/project/github/localstack/localstack/134293/output/108/3?file=true&allocation-id=64edfe78b7441c457e4a4496-3-build%2FABCDEFGH

Test order:
* `tests/aws/test_terraform.py::TestTerraform`
* `tests/aws/test_serverless.py::TestServerless::test_event_rules_deployed`

**Comment by viren-nadkarni** [comment]
cc: @bentsku

**Pull request merged**
