### PR TITLE
Kinesis Mock 0.1.6

### PR DESCRIPTION
**Pull request by etspaceman**

### CODE REVIEW

**Comment by whummer** [comment]
Thanks @etspaceman ! Can you please include a short summary of the latest changes, or cross-link the release notes for 0.1.5 here? Thanks

**Comment by etspaceman** [comment]
Sure:

https://github.com/etspaceman/kinesis-mock/releases/tag/0.1.5

**Comment by etspaceman** [comment]
Updated this to be 0.1.6, which resolves a bug with PutRecords:

https://github.com/etspaceman/kinesis-mock/releases/tag/0.1.6

**Comment by whummer** [comment]
LGTM, thanks @etspaceman ! 👍 (still waiting for the build to finish..)

**Review by whummer — APPROVED** [review]

**Pull request merged**
