### PR TITLE
Pin Cython<3 to fix PyYaml build

### PR DESCRIPTION
**Pull request by dfangl**
## Motivation
Since the release of Cython 3.0.0 an hour ago: https://pypi.org/project/Cython/#history , the installation of our dependency PyYaml broke.

See https://github.com/yaml/pyyaml/issues/601

## Changes
* Pin cython<3 for now, to ensure pyyaml builds correctly. We should remove the pin once the incompatibility is fixed.

### CODE REVIEW

**Review by alexrashed — APPROVED** [review]
Thanks for jumping on this so fast to unblock the build! 🚀

**Comment by makimkin** [comment]
It doesn't seem to be working 😥

**Comment by dfangl** [comment]
You are right, it is not. I can reproduce this locally, and I am currently trying to fix it.

**Comment by dfangl** [comment]
We will wait until a better solution is available. If we pin an earlier version, any install of awscli will automatically upgrade it again. Will wait for a better solution before disabling the build isolation before every build, as this will still influence the CLI experience heavily.

**Pull request closed without merging**
