### PR TITLE
perf: Replace function calls to literal syntax & remove unnecessary use of `comprehension`

### PR DESCRIPTION
**Pull request by iamrajiv**
## Description

It is unnecessary to use a comprehension just to loop over the `iterable` and create a `list/set/dict` out of it. Python has a specialized set of tools for this task: the `list/set/dict` constructors, which are faster and more readable.

Related: #5155 #5185

### CODE REVIEW

**Comment by thrau** [comment]
looks like there are still some test failures

**Comment by iamrajiv** [comment]
@thrau Yeah but I think they are not related to these files changes.

**Comment by thrau** [comment]
could you please rebase the branch to master and push again so we can get a green build? we only merge branches that pass the CI pipeline :slightly_smiling_face:

**Comment by whummer** [comment]
Thanks for updating the PR @iamrajiv 👍

**Pull request merged**
