### PR TITLE
Add some methods to build client async in TestUtils

### PR DESCRIPTION
**Pull request by netstart**
methods to build client async in TestUtils
Some async tests

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @netstart ! Can we first merge PR #839 , and then rebase this branch onto the changes made in #839 ? Would be great to merge in the entire set of changes, without running into conflicts. Thanks

**Comment by netstart** [comment]
It's OK to me. I thought that 839  PR was forgotten,

**Comment by netstart** [comment]
I will open again when 839  will be merged

**Comment by whummer** [comment]
@netstart Sorry, maybe my last message was not clear. Wasn't your PR adding additional capabilities, in addition to #839 ? Should we re-open this PR, resolve the conflicts, and get it merged? Thanks

**Comment by netstart** [comment]
I Understood, thank you for your atemption!
Don't worry, I will send other PR ;)

**Pull request closed without merging**
