### PR TITLE
Adding support for partial wildcards for S3 CORS

### PR DESCRIPTION
**Pull request by cloutierMat**
## Motivation

Fixing #10090 . AWS S3 CORS allows for partial wildcard `"http://*.example.com"`. The current changes will allow `OPTIONS` requests to go through instead of returning a 403 error

## Changes

- Replace the logic of looking for an exact match from Origin header to configured allowed origins by a regex that will match anything in lieu of the `*`.

## Testing

As mentioned on the issues description running the following command targeting an S3 bucket. With CORS configured as follow.

```
$ aws s3api get-bucket-cors --bucket foo --endpoint-url=http://localhost:4566                                                          
{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "AllowedMethods": [
                "GET",
                "PUT"
            ],
            "AllowedOrigins": [
                "http://*.example.com",
                "https://app.localstack.cloud",
                "http://app.localstack.cloud"
            ]
        }
    ]
}
```

```
$ curl -v --request OPTIONS 'http://127.0.0.1:4566/foo/' -H 'Origin: http://subd.example.com' -H 'Access-Control-Request-Method: GET'
```

### CODE REVIEW

**Comment by cloutierMat** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cloutierMat** [comment]
recheck

**Comment by cloutierMat** [comment]
Should I merge those latest changes coming from #10366 that fix the build to trigger again all of those pipelines?

**Comment by bentsku** [comment]
@cloutierMat yes, you can try! Very sorry again that those build was red, it was a bit tricky to detect the fork was coming from an outside repo. You can merge/rebase on master and we will see if it works.

**Review by bentsku — APPROVED** [review]
LGTM! Great change, quick and clean fix, and a nice set of tests validating it. You did a great job picking up the tools, thank you again for this fix!

**Comment by thrau** [comment]
welcome to the list of contributors @cloutierMat !

**Pull request merged**
