### PR TITLE
refactor SNS store to facilitate lookups

### PR DESCRIPTION
**Pull request by bentsku**
As we're currently working on persistence, I'd like to refactor the SNS store to facilitate lookup and have its data structures more aligned with how we are using them in the provider and to how AWS stores them.

Added some validations where I had questions on how AWS would behave.

### CODE REVIEW

**Review by thrau — APPROVED** [review]
nice cleanup! :broom: LGTM

**Comment by bentsku** [comment]
> nice cleanup! :broom: LGTM
> 
> 
> 
> but looks like pro tests are failing

Yes, looks like a lot of tests are failing 😅 I changed some logic and think I went a bit too much on some checks, will add some tests and validate this with AWS.

**Comment by thrau** [comment]
@bentsku are we merging this?

**Comment by bentsku** [comment]
@thrau Yes, I think so? If we're breaking persistence, now is the way to go. We can also wait a bit to be closer to `v2`, but it's something I wanted to be out before v2, that'd be great.

**Pull request merged**
