### PR TITLE
Added rudimentary path parameter support for AWS_PROXY

### PR DESCRIPTION
**Pull request by KamuelaFranco**
First iteration of fix for #229.

### CODE REVIEW

**Comment by whummer** [comment]
Hey @KamuelaFranco, I think this is a great start and generally going into the right direction, I'd be happy to help out to get this done. Have you been able to set up a basic test that we can start from? Thanks

**Comment by KamuelaFranco** [comment]
@whummer I'll try to get a test out in a few hours. At the moment, I think most of the functionality is working.

**Comment by KamuelaFranco** [comment]
@whummer When using ```(. .venv/bin/activate; DEBUG= PYTHONPATH=`pwd` nosetests --with-coverage --logging-level=WARNING --nocapture --no-skip --exe --cover-erase --cover-tests --cover-inclusive --cover-package=localstack --with-xunit --exclude='.venv.*' tests/integration/test_api_gateway.py)```, and specifically looking at `test_api_gateway.py`, is there any way to see console output? I'm not sure I follow how the tests are running.

**Comment by whummer** [comment]
@KamuelaFranco Since we're using the `--nocapture` flag, you should be able to see any `print(...)` outputs that are in your tests.
You can also try to set the variable `DEBUG=1` in the command above, that should give you more detailed output of the backend services (which are running in separate processes).

**Comment by KamuelaFranco** [comment]
@whummer I'm looking at `test_api_gateway.py`'s `connect_api_gateway_to_http_with_lambda_proxy`. Where does this actually get called? I've got a `print` in here that I don't ever see.

**Comment by whummer** [comment]
@KamuelaFranco This function hasn't been called anywhere because the `test_api_gateway_lambda_proxy_integration` function in `test_api_gateway.py` was commented out. :) (a while ago we decided to merge another PR of yours, #224, and left that part commented out temporarily.)

I have now enabled this test in PR #281 , please rebase onto latest `master`. Hope we can use this as a starting point.

**Comment by KamuelaFranco** [comment]
@whummer I believe I've merged correctly, but the tests are now just hanging. Not sure where to begin here.

**Comment by whummer** [comment]
@KamuelaFranco Looks like the following lines have gone missing in the merge: https://github.com/localstack/localstack/pull/251/files#diff-6577b2fe3a6c5d8be2158124a1f1e71eL118

If you do another rebase to current `master`, the error logging has been improved in 0a5fba8c77181a59a9a741fd3da47b9d4e022bba. You should now see the error message when your test fails/hangs.

Do we already have a test case for this feature? Would be great if you could push it. Thanks

**Comment by KamuelaFranco** [comment]
Two things outstanding with this PR:

1. Test case for Lambda proxy integration with path params and also empty body to be returned with just headers
2. The fuzzy search needs to be replaced with a proper regex approach because there are false positives right now if you type an endpoint incorrectly and it shouldn't match anything

**Comment by whummer** [comment]
Thanks @KamuelaFranco , I'm taking over this PR from here. 👍 I already have a branch running locally, hopefully will be able to push it later today.

**Comment by whummer** [comment]
Again, thanks for this PR! The new functionality has been merged in #302 . Please open a new new issue and/or PR if the current implementation does not fully cover your use case. Thanks!

**Pull request closed without merging**
