### PR TITLE
fix Transfer-Encoding "chunked" on empty responses

### PR DESCRIPTION
**Pull request by whummer**
Avoid returning `Transfer-Encoding` headers for HTTP 204 responses. Should fix the currently failing build on `master`.

Currently seeing connection/protocol errors like below:
```
            except (HTTPException, SocketError) as e:
                # This includes IncompleteRead.
>               raise ProtocolError("Connection broken: %r" % e, e)
E               urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

.venv/lib/python3.8/site-packages/urllib3/response.py:458: ProtocolError
```

The issue is that `Transfer-Encoding` is being returned from some of the Flask APIs (Lambda DELETE operations that return a 204 status), which newer versions of `urllib3` cannot handle.

Was doing a quick search across recent changes in `urllib3`/`flask`/`hypercorn` to find out where this new behavior got introduced, but couldn't pinpoint the change so far.
 
The change to remove `Transfer-Encoding` seems safe in the general case, as 204 HTTP responses expect no content to be sent along with the response.

### CODE REVIEW

**Comment by alexrashed** [comment]
The origin of the issue seems to be the [2.1.0 release of werkzeug](https://github.com/pallets/werkzeug/releases/tag/2.1.0).
The [changelog](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) mentions the following changes concerning the `Transfer-Encoding`:
> The development server uses Transfer-Encoding: chunked for streaming responses when it is configured for HTTP/1.1. [#2090](https://github.com/pallets/werkzeug/issues/2090), [#1327](https://github.com/pallets/werkzeug/issues/1327), [#2091](https://github.com/pallets/werkzeug/pull/2091)

Werkzeug is used by Flask, which in turn then sends a response which defines the `Transfer-Encoding: chunked` on responses with an empty body. This in turn causes urllib to raise an `InvalidChunkLenth` exception (which has been discussed [here](https://github.com/urllib3/urllib3/issues/1516), and implemented [here](https://github.com/urllib3/urllib3/pull/1888)).

I still need to investigate a bit more, but the safest fix for now would be to pin `werkzeug` to the latest version before `2.1.0`, which is `2.0.3`.

**Comment by alexrashed** [comment]
The fix - pinning werkzeug to the previous release - works well.
I will further investigate the issue with werkzeug later on, but from my perspective this PR is ready to be reviewed and merged. :)
/cc @whummer @dominikschubert

**Comment by whummer** [comment]
Perfect, thanks for the quick fix @alexrashed ! 💯

**Comment by alexrashed** [comment]
The root cause was werkzeug breaking the HTTP 1.1 spec, as reported here: https://github.com/pallets/werkzeug/issues/2375
I just verified that the fix (https://github.com/pallets/werkzeug/pull/2377) solves the issue.
This means we can remove the Werkzeug dependency pin as soon as the next bugfix release is out.

**Pull request merged**
