### PR TITLE
Allow the main docker container name to specified

### PR DESCRIPTION
**Pull request by yonahforst**
addresses #2738

### CODE REVIEW

**Comment by whummer** [comment]
Thanks for this PR @yonahforst ! Looks like we still have a minor linting issue in our CI builds - can we please fix it? (You can also run `make lint` locally to reproduce). Thanks
```
./localstack/config.py:158:1: E302 expected 2 blank lines, found 1
def has_docker():
^
```

**Comment by yonahforst** [comment]
@whummer  - Done! I have some trouble running any of the `make` commands, something to do with the python installation on my mac, but i think i fixed the linting problem.

**Comment by whummer** [comment]
Looks great, thanks @yonahforst ! 👍

**Comment by yonahforst** [comment]
@whummer - this doesn't seem to have worked :(

**Pull request merged**
