### PR TITLE
Make AWS region name configurable for tests

### PR DESCRIPTION
**Pull request by joe4dev**
## Motivation

We should have a configuration to change the test region. For cross-account tests, we should be able to configure the region in order to test cross-account tests within the same region.

Discovered during testing of the Lambda invocation loop rework https://github.com/localstack/localstack/pull/8970
/cc @dfangl @dominikschubert 

## Changes

Makes the AWS region name configurable in tests.

### CODE REVIEW

**Comment by joe4dev** [comment]
We could also consider dropping the `_NAME` suffix to match the `AWS_REGION` config 🤔

**Review by viren-nadkarni — APPROVED** [review]
🚀

**Review by dfangl — APPROVED** [review]

**Comment by joe4dev** [comment]
> We could also consider dropping the `_NAME` suffix to match the `AWS_REGION` config 🤔

Align environment variable naming with AWS CLI using `TEST_AWS_REGION` without the `_NAME` suffix.

Removing the suffix `_NAME` aligns the environment variable naming with the AWS CLI using `AWS_REGION` (which overwrites `AWS_DEFAULT_REGION`).
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by joe4dev** [comment]
Flaky arm64 test unrelated and reported in flaky test list (already know flake)

**Pull request merged**
