### PR TITLE
Combine OpenSearch and Elasticsearch backends

### PR DESCRIPTION
**Pull request by silv-io**
This PR:

- adds Elasticsearch functionality to OpenSearch
- migrates the Elasticsearch service to ASF
- changes the Elasticsearch implementation to relay to OpenSearch instead of handling the requests itself

### CODE REVIEW

**Comment by alexrashed** [comment]
Fixes https://github.com/localstack/localstack/issues/4686

**Comment by thrau** [comment]
looks like we have some conflicts. could you rebase? i'll review it tomorrow :-)

**Review by thrau — APPROVED** [review]
looks great folks, fantastic work! :clap: 

just one thing to make sure, because i couldn't fully comprehend this by looking through the code:
the default elasticsearch version is pre-seeded into the container image https://github.com/localstack/localstack/blob/b09c4f89481cec43b3d126c15050910cae81e9d1/Dockerfile#L188-L191

we now set this to: https://github.com/localstack/localstack/blob/9613fc586833ccbc2ad04e19bbedb1227d056588/localstack/constants.py#L103-L104

how are we making sure the correct pre-seeded version is used by default? previously that was done just via the version tag, which now obviously mismatches `Elasticsearch_7.10 != 7.10.0`

**Comment by alexrashed** [comment]
Good question! We aligned the versions with the OpenSearch engine versioning.
The cluster manager takes the "OpenSearch-scheme version string" ("Elasticsearch_7.10") and extracts the engine type ("Elasticsearch"):
https://github.com/localstack/localstack/blob/9613fc586833ccbc2ad04e19bbedb1227d056588/localstack/services/opensearch/cluster_manager.py#L166

The engine type is later on to use the right cluster implementation (for elasticsearch or opensearch).
Later on the `versions.py` is used to determine the specific version for a minor version (Elasticsearch_7.10 -> Elasticsearch_7.10.0):
https://github.com/localstack/localstack/blob/9613fc586833ccbc2ad04e19bbedb1227d056588/localstack/services/opensearch/versions.py#L181

**Pull request merged**
