### PR TITLE
Add temporary support for nodejs16.x runtime

### LINKED ISSUE #6021: bug: Lambda won't execute if using ES6 export syntax
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a lambda using E6S export syntax:

```
export const handler = (event) => {
  console.log("hello world");
  console.log(event);

  return event;
};
```

with `"type": "module"` set in my `package.json` I get the following error:

```
ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"Must use import to load ES Module: /var/task/index.js\nrequire() of ES modules is not supported.\nrequire() of /var/task/index.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.\nInstead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.\n","code":"ERR_REQUIRE_ESM","stack":["Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/index.js","require() of ES modules is not supported.","require() of /var/task/index.js from /var/runtime/UserFunction.js is an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which defines all .js files in that package scope as ES modules.","Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove \"type\": \"module\" from /var/task/package.json.","","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Module.require (internal/modules/cjs/loader.js:952:19)","    at require (internal/modules/cjs/helpers.js:88:18)","    at _tryRequire (/var/runtime/UserFunction.js:75:12)","    at _loadUserApp (/var/runtime/UserFunction.js:95:12)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)"]}
```

I have provisioned the lambda with terraform:

```
resource "aws_lambda_function" "test" {
  filename         = "lambda.zip"
  function_name    = "test-function"
  role             = aws_iam_role.lambda.arn
  handler          = "index.handler"
  source_code_hash = data.archive_file.lambda_my_function.output_base64sha256

  runtime = "nodejs14.x"
}
```

### Expected Behavior

I'd expect the lambda to execute successfully without any errors.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker compose up with example docker-compose.yaml file:

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Infrastructure is provisioned with the terraform in the example above. The code runs fine when using CommonJS.

Lambda is triggered with the following command:

```
awslocal lambda invoke --function-name test-function --invocation-type Event --cli-binary-format raw-in-base64-out --payload '{ "key": "value" }' output.txt
```

### Environment

```markdown
- OS: macOS Mojave 10.14.6 (18G9216)
- LocalStack: latest
```

### Anything else?

_No response_

### LINKED ISSUE #6111: feature request: Support mapping of runtime to container name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The use case I have in mind is to run Node 16.x Lambdas - the default container registry is `lambci/lambda` which is effectively abandoned. [Not even Node 14.x has been published](https://github.com/lambci/docker-lambda/pull/330). However, switching the registry over to [`amazon/aws-lambda-nodejs`](https://hub.docker.com/r/amazon/aws-lambda-nodejs) still fails to pull the container, since localstack is looking for the tag `nodejs16.x`. I'd like to be able to specify that if the runtime is `nodejs16.x` it just looks for tag `16`.

### 🧑‍💻 Implementation

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pksunkara**
This PR fixes #6111 and fixes #6021.

This PR is built around the same logic as 3b52abf39e093cb503add318c205264a7c6c67ff to temporarily support more runtime's using @mlupine fork of lambci/lambda. It also removes some custom logic added in #3688 for nodejs14.x.

Need to wait until https://github.com/mLupine/docker-lambda/issues/10 is merged and released.

### CODE REVIEW

**Comment by pksunkara** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by dfangl — COMMENTED** [review]
Hi! First of all, thank you for tackling this!
I only took a quick look, but it looks good. Will properly review once the images are available.

Please also add the node16 runtime to `NODE_TEST_RUNTIMES` in tests/integration/awslambda/test_lambda.py to allow automatic testing of nodejs 16 (the lambdas used are quite basic and should work in node 16 as well, if nothing important changed).

**Comment by pksunkara** [comment]
@dfangl This is ready since the underlying PR has been merged.

**Comment by dfangl** [comment]
@pksunkara It seems the linter is failing. Can you run `make format` and `make lint` and resolve the issues? Then we can get this over the line!

**Comment by pksunkara** [comment]
Done.

**Comment by pksunkara** [comment]
Need some help figuring out how to fix the failing test.

**Comment by pksunkara** [comment]
I do. Thanks.

**Comment by dfangl** [comment]
As explanation: We use a snapshot utility (see #5825 for example) to test responses of LocalStack. It seems this error is thrown if the snapshots do not exist for the given test (in this case, the nodejs16 tests) yet. We will try to come up with a better explanation in the error logs.

**Review by dfangl — APPROVED** [review]
LGTM! Thanks for this contribution!

**Pull request merged**
