### PR TITLE
upgrade flake8 and black

### PR DESCRIPTION
**Pull request by alexrashed**
## Motivation
The latest update of pyproject-flake (6.1.0) recently broke the build.
We pinned the version with https://github.com/localstack/localstack/pull/9215 to unblock the pipeline.
This PR removes the pin and upgrades black, flake8, and all related packages, to their latest versions.

## Changes
- Upgrade black, flake8, and all related packages, to their latest versions. 
- Fix new linting errors (flake8 upgrade).
- Reformat code with new black version (black upgrade).

### CODE REVIEW

**Comment by thrau** [comment]
@alexrashed wouldn't it be easier to just exclude the offending rules (like `E721`) from our linter?

**Comment by alexrashed** [comment]
@thrau: Why do you think this would be a better way? There were only a few violations, and I for myself think that E721 is quite useful. Explicit type checks are rarely useful, and they could be excluded if you really think.

**Comment by thrau** [comment]
i was going to say that i generally would prefer a stable linter/formatting config rather than being subject to updates. but after thinking about it for a few minutes, i think it's actually the other way round. standards are better :dagger:

**Review by thrau — APPROVED** [review]
LGTM, let's move forward

**Comment by alexrashed** [comment]
Superseded by https://github.com/localstack/localstack/pull/9399

**Pull request closed without merging**
